### ISSUE TITLE
Firefox 55.0.1 This add-on is not compatible with your version of Firefox. 

### ISSUE THREAD

**Issue by yodatak** [wallabag/wallabagger#100]
On fedora 26 on Fedora 55.0.1 on https://addons.mozilla.org/en-US/firefox/addon/wallabagger/
It mark me the  extension incompatible

**Comment by tcitworld** [comment]
Are you sure you're using Firefox 55 ? It should work with it, unless Fedora did something strange.
>  Works with Firefox 52.0 and later 
https://addons.mozilla.org/en-US/firefox/addon/wallabagger/versions/?page=1#version-1.4.3

**Comment by guiweber** [comment]
Works fine for me on Fedora 26, FF 55.0.1 and Wallabager 1.4.3.

Are you sure you have updated to the latest Wallabager version? Maybe you have turned off automatic updates and are stuck on an older version.

**Comment by yodatak** [comment]
Works now , do know why sorry for that ^^
