### ISSUE TITLE
No addon-settings in Firefox for  Android

### ISSUE THREAD

**Issue by Skyr** [wallabag/wallabagger#101]
In Android (Extras -> Add-ons -> Wallabagger), the plugin only shows a (even truncated) description of the addon, plus, at the bottom, the "deactivate" and "deinstall" buttons. The rest of the screen is blank, other add-ons show here their respective settings.
I'm using Wallabagger 1.4.3 and FF for Android 55.0.2.

**Comment by tcitworld** [comment]
AFAIK we don't support Firefox or Chrome on Android. Use the share action provided by the Android app instead.

**Comment by Skyr** [comment]
Ahem… * smacks head * should have thought of that ;-)
