### ISSUE TITLE
Clicking a second time on the Star or Checkmark icon does not unto the action

### ISSUE THREAD

**Issue by guiweber** [wallabag/wallabagger#102]
If you click by mistake on the star or checkmark icon while adding a page, you may be tempted to click on the same icon again to bring the page back to its default state. However, clicking a second time on those icons has no effect, even though the icon goes back to the original color giving the impression the the action has been undone.
![capture](https://user-images.githubusercontent.com/7825368/29488145-be828d64-84d2-11e7-8384-f6dc3749226e.PNG)

This was tested in Wallabag 1.4.3 on FF 55.0.2

**Comment by Rurik19** [comment]
fixed in v1.4.4
