### ISSUE TITLE
Tooltips for checkmark and star icon always say "Unset"

### ISSUE THREAD

**Issue by guiweber** [wallabag/wallabagger#103]
The tooltips for the star and checkmark icons are supposed to change depending on the status of the page. For example, if the page is not already starred, the tooltip should display string `data-seticon-title` which is "Set this article as starred into Wallabag". If the page is already starred, the tooltip should display `data-unseticon-title` which is "Unset this article as starred into Wallabag". However, the tooltip always displays the strings with "Unset".

![capture](https://user-images.githubusercontent.com/7825368/29488423-9e0635f8-84d8-11e7-92b0-0e275b8ec955.PNG)

This was tested in Wallabag 1.4.3 on FF 55.0.2
This issue may be linked to #102

**Comment by Rurik19** [comment]
fixed in v1.4.4
