### ISSUE TITLE
Chrome extension and wallabag.it

### ISSUE THREAD

**Issue by zaslowe** [wallabag/wallabagger#104]
Hi - would it be possible to add directions for how to set up the Chrome extension if you use wallbag.it? Documentation says to create a Client ID and Client secret locally, but we can't do this if we're using wallabag.it.

Thanks.

**Comment by Rurik19** [comment]
Hi!  Client ID and Client secret  should be created in the wallabag.it's "API clients management" menu, just create an client there and copy values to wallabagger setup.

**Comment by nicosomb** [comment]
@zaslowe Thanks to the @Rurik19's answer, you should manage to configure it. 
If you still have issues, contact me at nicolas@wallabag.it.
