### ISSUE TITLE
settings resetted

### ISSUE THREAD

**Issue by tvelter** [wallabag/wallabagger#106]
I have wallabager installed with firefox 55.0.2, and linux.
When i restart my browser, my wallabager button is not working anymore ("loading wallabag API") and the settings are blanked.
I need to remove the extension, reinstall it, and then disable, enable and get the token (the settings magically reappear after disabling/enabling the extension). Then I need to restart my browser and I can use the button until the next closure of firefox.
please let me know if you need more information

**Comment by Simounet** [comment]
Hello,
Was it working before the update to 55.0.2?
Can you follow these steps:
- enable the debug mode into the wallabagger settings
- go to about:debugging#addons
- check in Enable add-on debugging
- click on wallabag debug link
- click on ok to accept incoming connections
- add some page through the context-menu
- give us the entries on the console tab of the new window opened

**Comment by tvelter** [comment]
I'm not sure , but I think the problem appeared with firefox 55.x(upgrade from 54).
I did activate the debug mode, but the console remains empty when the bug happen(there is some activity when I reinstall and have the add-on working as expected).


On September 29, 2017 12:40:42 AM GMT+07:00, Simon Alberny <notifications@github.com> wrote:
>Hello,
>Was it working before the update to 55.0.2?
>Can you follow these steps:
>- enable the debug mode into the wallabagger settings
>- go to about:debugging#addons
>- check in Enable add-on debugging
>- click on wallabag debug link
>- click on ok to accept incoming connections
>- add some page through the context-menu
>- give us the entries on the console tab of the new window opened
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wallabag/wallabagger/issues/106#issuecomment-332910652

-- 
Sent from my phone. Please excuse my brevity.

**Comment by tvelter** [comment]
upgrade to firefox 56.0 has solved the problem, now let's wait for the big changes from firefox 57 ...
