### ISSUE TITLE
Configuring the Firefox Extension for the paid hosted use case.

### ISSUE THREAD

**Issue by antoan** [wallabag/wallabagger#107]
Version 1.4.4

The documentation seems to cover everything but the paid hosted service at wallabag.  
![screenshot from 2017-10-05 15 32 13](https://user-images.githubusercontent.com/1454427/31232809-d7d16d46-a9e2-11e7-8333-cdc725654779.png)
I'm still trying to figure how to acquire a Client ID and a Secret in my case? 

* HTTPS does not seem to work, the URL check for this fails silently, well almost -  a red border is shown around the URL box.
* API token is expired.

Broken links: 
https://rurik19.github.io/wallabagger/installation.md
https://rurik19.github.io/wallabagger/usage

**Comment by tcitworld** [comment]
`v2.wallabag.org` is closed. I guess you mean `app.wallabag.it`. Go to the developer section of your wallabag instance and get an Client ID & secret.

**Comment by Rurik19** [comment]
Hi! where are those broken links?
