### ISSUE TITLE
Wallabagger should be able to get title (and content) from paywalled sites

### ISSUE THREAD

**Issue by msjoberg** [wallabag/wallabagger#108]
I have a problem with paywalled sites such as [Linux Weekly News](https://lwn.net/). Naturally Wallabag is not able to independently fetch the content directly as you need to log in to see it (for recent articles in the LWN case). However, when using an extension running in Firefox it should be able to extract at least the page title (and possibly even the text content) directly from the rendered page in Firefox. In fact Wallabagger seems to be doing this as the title is briefly shown when you click the button to save the page. However, after the page has been saved to Wallabag it is replaced with the "No title found" that is produced by Wallabag itself (as it tries to unsuccessfully fetch the page itself). Wallabag should honour the title sent by the extension...

**Comment by Rurik19** [comment]
Hi! The ability of saving content from  client apps like wallabagger will work in the upcoming 2.3 version of wallabag. Then we can implement this in the extension as well.
