### ISSUE TITLE
addon seems to be loggin every browser request

### ISSUE THREAD

**Issue by pixelyo** [wallabag/wallabagger#109]
```
172.18.0.1 - - [01/Nov/2017:17:33:35 +0000] "GET /api/entries/exists.json?url=https://duckduckgo.com/******************* HTTP/1.0" 200 36 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
```
this is one of the browser request, i am using the [wallabag docker-compose setup](https://github.com/wallabag/docker#docker-compose)

why is the addon doing this?

**Comment by Simounet** [comment]
You might have activated the `indicate if page already saved` option, don't you?

**Comment by pixelyo** [comment]
yep that's it :) thank you
