### ISSUE TITLE
Firefox bug

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabagger#11]
In firefox there is a bug with a list of found tags. And dots around input field is not very  nice
![image](https://cloud.githubusercontent.com/assets/1955806/20705464/db915708-b644-11e6-9a3f-7ce035ec6bae.png)

**Comment by Simounet** [comment]
I think that you can use this: https://github.com/Simounet/wallabagger/commit/4cfe559ecad157dc372799c22aa45de44700b77c .

**Comment by Rurik19** [comment]
Too much white space in the bottom after open window
I think using js is required. Please look at https://github.com/Rurik19/wallabagger/commit/940470ccf2934925e69f9df8ecda8686d14b9e0a
