### ISSUE TITLE
Cannot change title, archive, star, add tags

### ISSUE THREAD

**Issue by kode9** [wallabag/wallabagger#110]
Hello,

When I do any of these actions, _nothing_ happens.
I don't have **any** logs neither in the server logs or in the wallabag logs.

For example I add tags, they appear in the popup, but there are no request to the server (and obvously are not added in the wallabag web app). If i close and reopen the popup there are no tags.
Same goes when editing the title, archive or star the title.
All these features work fine in the wallabag web app itself.

Add and remove an article function properly, though.

Anything I can do to understand what's going on ?

Arch Linux
Firefox 56.0.2 (64-bit)
Wallabagger 1.4.4
Wallabag 2.2.3
HTTPS ON
All checklist OK

Thanks

**Comment by Simounet** [comment]
Hi,
Can you follow these steps:
- enable the debug mode into the wallabagger settings
- go to about:debugging#addons
- check in Enable add-on debugging
- click on wallabag debug link
- click on ok to accept incoming connections
- add some page through the context-menu
- give us the entries on the console tab of the new window opened

**Comment by Rurik19** [comment]
Also, please disable all security-related addons it there is any. If after that wallabagger begins to work, set up those extensions.

**Comment by kode9** [comment]
Thanks for the quick answers !

@Rurik19 So I first deactivated all other extensions, but it didn't change anything.

After that I followed @Simounet steps (still with only wallabag enabled)

Server log
```
CLIENT_IP - - [10/Nov/2017:12:37:10 +0100] "POST /api/entries.json HTTP/1.0" 200 3034 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
CLIENT_IP - - [10/Nov/2017:12:37:12 +0100] "GET /assets/images/f/2/f22c2cf7/9e805db3.jpeg HTTP/1.0" 200 13008 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
```
```js
postMessage: {"response":"setup","data":{"Url":"WALLABAG_DOMAIN","ApiVersion":"2.2.3","ClientId":"CLIENT_ID","ClientSecret":"CLIENT_SECRET","UserLogin":"USER_LOGIN","UserPassword":"USER_PASSWORD","ApiToken":"API_TOKEN","RefreshToken":"REFRESH_TOKEN","ExpireDate":1510317034870,"isTokenExpired":false,"AllowSpaceInTags":false,"AllowExistCheck":true,"Debug":true}}  background.js:178:23

postMessage: {"response":"tags","tags":[]}  background.js:178:23

postMessage: {"response":"info","text":"Saving the page to wallabag ..."}  background.js:178:23

postMessage: {"response":"article","article":{"id":298,"is_starred":0,"is_archived":0,"title":"OVH est down - Pas de paniiiiiiique ! - Korben","url":"https://korben.info/ovh-down-de-paniiiiiiique.html","tags":[],"domain_name":"korben.info","preview_picture":"WALLABAG_DOMAIN/assets/images/f/2/f22c2cf7/9e805db3.jpeg"}}  background.js:178:23

Error: Failed to update article WALLABAG_DOMAIN/api/entries/298.json
NetworkError when attempting to fetch resource.  wallabag-api.js:136:23

// NOTE: This is when I edit the title
Error: Failed to update article WALLABAG_DOMAIN/api/entries/298.json
NetworkError when attempting to fetch resource.
```

I obviously obfuscated `CLIENT_IP` `WALLABAG_DOMAIN` `CLIENT_ID` `CLIENT_SECRET` `USER_LOGIN` `USER_PASSWORD` `API_TOKEN` `REFRESH_TOKEN`.

The corresponding function in `wallabag-api.js`
```js
PatchArticle: function (articleId, content) {
        let entryUrl = `${this.data.Url}/api/entries/${articleId}.json`;
        return this.CheckToken().then(a =>
                this.fetchApi.Patch(entryUrl, this.data.ApiToken, content)
            )
            .catch(error => {
                throw new Error(`Failed to update article ${entryUrl}
                ${error.message}`);
            });
    },
```

Nothing in `prod.log`.

Note that I didn't restart firefox at any point if that's a concern.

Seeing the error, and if all seems correct for you, I'm guessing it could be related with some of my server settings.
AFAIU, the access to `WALLABAG_DOMAIN/api/entries/298.json` is the correct behavior, I'll check if something prevent it on the server side.

**Comment by kode9** [comment]
When I try to add a tag (`foo`):

**Comment by Rurik19** [comment]
It seems that your server blocks PATCH http method.

**Comment by kode9** [comment]
@Rurik19 Well that's possible, I'm on a shared host and I know they block `PROPFIND` for example.

Anyway, a `curl` direct call does not work either, so this is definitely a server-side issue, not a wallager, so I'm closing this. I'll open an issue there if need be.

Thanks for the help !

**Comment by kode9** [comment]
Sorry for closing/opening like this,

Since all functionalities work in the webb app, I just checked what call is used :
```
POST /new-tag/298
POST /remove-tag/298/10
POST /edit/298
```

Now `PATCH` is probably best suited if I understand correctly, but would it make sense to have a _compatibility_ option that use `POST` instead of `PATCH` ?

I'll let you close this issue after that :p
Thanks again.

**Comment by Rurik19** [comment]
As for tags, we have POST edit and DELETE method, but for entry, POST method is used for creating entry, not for edit. If you want you should create an issue for changing the wallabag API.

**Comment by georgedorn** [comment]
Is there anything approaching a fix for this?  Or a corresponding issue on the server side I can look into?

**Comment by Simounet** [comment]
Sorry for the late reply. If this is still an issue for you, you should post an issue on the [wallabag's repo](https://github.com/wallabag/wallabag/issues). I don't think wallabagger can do anything for you right now.
I'm closing this issue but feel free to reopen it if you have any other concern about this precise topic.
Have a nice day.
