### ISSUE TITLE
Can't add an article to my wallabag wallet (framasoft fork)

### ISSUE THREAD

**Issue by quoidautre** [wallabag/wallabagger#111]
Hi,
I've just installed the extension (1.4.4) on Firefox (56.0.2) on Window$.
My framabag.org page is open.

If I click on the "W" button, the popup open.
But the "Saving the page to wallabag ..." button is NOT clickable. So, I can't add the article in my wallet :(.

Can you help me please ?
Thanks.

The debug mode is ON, [here](https://framapic.org/iryExSWCwxm3/KR22PulDT6dk.jpg)
F.

**Comment by Rurik19** [comment]
It seems that you don't set up the extension at all

**Comment by quoidautre** [comment]
Hi,

Thanks. So, I put the framabag.org in th url for checking : Ok and API version 2.2.2.
I create a client in framabag (+token, etc).

I must type my connection's password to https://framabag.org ?. And the login is this one or the "user login" in the customer managment : https://framabag.org/developer ?

Regards.
F.

**Comment by Rurik19** [comment]
I don't really know what framabag.org is and how it organizes users, but as for wallabag servers yes, you have to tape user login and password

**Comment by quoidautre** [comment]
Ok, it's working for now :). Thanks a lot.

But, the image on the top left of the popup is broken.

**Comment by Rurik19** [comment]
can you make a screenshot of the broken image?

**Comment by quoidautre** [comment]
ok, [here](https://framapic.org/xOIozr8AhPBK/ocQLbrsht4PK.jpg).

**Comment by nicosomb** [comment]
@quoidautre is the bug still there?

**Comment by quoidautre** [comment]
Hi,
No, I can add an article, and I see the icon :).

Thanks.
F.
