### ISSUE TITLE
Firefox: text fields cropped in config page

### ISSUE THREAD

**Issue by gnppn** [wallabag/wallabagger#113]
Hello,

When configuring the extension in Firefox 57, the bottom of the text fields is cropped. This is a problem when client IDs and secrets contain a "_" character, which is invisible to the user.

![image](https://user-images.githubusercontent.com/22668283/33126982-dbfbc73a-cf86-11e7-92d4-ad9c1fb200da.png)

Could you please display the whole characters in these fields?

Thanks in advance.

**Comment by Simounet** [comment]
Hi Guénaël,
Are you using a custom font-size? I can't reproduce this issue. I will remove the fixed height values anyway.

**Comment by gnppn** [comment]
Hi,

This is a fresh Firefox 57 install with Windows 10 scaling à 100%. No personalization on this front. Could it be another extension messing with it?

**Comment by Simounet** [comment]
I don't think so. I don't have any Windows machine right now. I'll look into this later.

**Comment by nicosomb** [comment]
Can't reproduce on FF 57 with macOS.

**Comment by Simounet** [comment]
Ok, I get it on Linux / Fx 59 and I have a fix. I'll test it a little bit then push it.

**Comment by Rurik19** [comment]
@Simounet  make it in Development branch - it contains new option page
