### ISSUE TITLE
Is it possible to have a browser based's specific design

### ISSUE THREAD

**Issue by theotix** [wallabag/wallabagger#119]
Hello,
I'm not very convenient with web extentions, so because of [this issue](https://github.com/wallabag/wallabagger/issues/53) I was wondering if it was possible to put a specific design for each browser to have a better visual integration in them.
For example it's could be easy to have a better integration in Firefox using their [design system documentation](http://design.firefox.com/photon/welcome.html). 

If it's possible, I can start designing and code some html/css/js to achieve that.

**Comment by Rurik19** [comment]
We are going to rework styles of popup and options to remove external references, why not to look at that Firefox design system? it seems quite reasonable

**Comment by theotix** [comment]
I'm happy to hear that! 
Also I didn't found a design design or a style guide for Opera browser, but for Chrome maybe we can look at the [material guidelines](https://material.io/guidelines/#introduction-principles).

**Comment by Rurik19** [comment]
As for the general question - no, I don't think that we should have separate designs for each browser - just **good** one.

**Comment by Simounet** [comment]
I agree with @Rurik19 about having only design. It might be difficult for such a little team to maintain multiple designs. We have make ours better. Usually, I love Mozilla's work but I think that we are using [material design](https://material.io/guidelines/) for wallabag and it is more precise about everything. We doesn't have many screens to design so I think we can use it for inspiration (not importing the whole thing). In my opinion, this could be great to share the same design, action buttons, etc.

**Comment by theotix** [comment]
Okay, too bad. But I understand 🙂
