### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by ThibaudDauce** [wallabag/wallabagger#12]
Add a context menu to right-click on links and "Add to wallabag"

- https://developer.chrome.com/extensions/contextMenus
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus

Thanks for the great work!

**Comment by Simounet** [comment]
I did the dev and it is working locally. I will package this later.

**Comment by Rurik19** [comment]
done with #20
