### ISSUE TITLE
not working in firefox-esr

### ISSUE THREAD

**Issue by jonazc** [wallabag/wallabagger#124]
unfortunately addon is not working on firefox-esr. When I add the server url and click "check url" simply nothing happens.

**Comment by Simounet** [comment]
Which ESR version are you using? Firefox 52?

**Comment by jonazc** [comment]
yes, of course the up-to-date one :)

**Comment by Simounet** [comment]
Do you have any extension that can interfere with it? Can you try it on a fresh profile?
Can you follow these step:
- enable the debug mode into the wallabagger settings
- go to about:debugging#addons
- check in Enable add-on debugging
- click on wallabag debug link
- click on ok to accept incoming connections
- add some page through the context-menu
- give us the entries on the console tab of the new window opened

**Comment by jonazc** [comment]
oh true it works in fresh profile, I will try to figure out which addon interferes there...

**Comment by jonazc** [comment]
unfortunately I cant tell you, it just worked with the last try..

**Comment by jonazc** [comment]
ok, I think I figured it out. But I still don't know why the config worked suddenly :) However, i had a similiar issue when trying to save my first article, just the text "saving to wallabag" appeared, the icon turned red and then black again.

The problem was uMatrix that I have configured to block all 3rd party calls. It was not enough, that I already deactivated wallaback.myserver.com, but I also had to unblock the domain being called as 3rd party. You can do this in uMatrix by clicking on the domain name in the upper left and choose `*`

**Comment by Simounet** [comment]
Ok, thanks for this information.
