### ISSUE TITLE
Cannot get token (Firefox 58.0.1)

### ISSUE THREAD

**Issue by midgetcylinder** [wallabag/wallabagger#127]
I cannot get the access token on the Firefox extension. I have checked that the client ID and client secret are correct. I have also attempted to use both the default "wallabag" user and another user that I created. Neither username/password combination allows me to get an API token.
![image](https://user-images.githubusercontent.com/36010068/35640286-f4400764-0679-11e8-97a5-b1d0389821e1.png)

**Comment by tcitworld** [comment]
Not related, but please stop using v2.wallabag.org

**Comment by midgetcylinder** [comment]
Which URL should I use?

**Comment by tcitworld** [comment]
Either https://framabag.org (free, with some limitations), or https://wallabag.it. You need to export your data from v2.wallabag.org first.

**Comment by midgetcylinder** [comment]
I got it working with framabag. Thanks for the help!

**Comment by arooni** [comment]
@tcitworld do you know whether or not the 1000 article limit with framabag is for *all articles* or unread articles?
