### ISSUE TITLE
Extension Install Fails from Chrome Web Store

### ISSUE THREAD

**Issue by DeanCording** [wallabag/wallabagger#128]
When trying to install the Wallabag extension in Chromium on Ubuntu 17.10 from the Chrome Web Store, I get the following error message:

`Package is invalid. Details: 'Default locale is defined but default data couldn't be loaded.'.`

**Comment by Simounet** [comment]
Hi there,
Sorry for the late reply. Is it still a thing or can we close this issue?

**Comment by Simounet** [comment]
I'm closing this old issue. Feel free to reopen it.
