### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by ThibaudDauce** [wallabag/wallabagger#13]
Add a keyboard shortcut in the config to add a webpage to wallabag.

- https://developer.chrome.com/extensions/commands
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands

I'm planning to deprecate the [Firefox extension](https://github.com/wallabag/firefox-ext-v2) for this one :-) Just missing these two features (shortcut and context menu) but it's not a big deal ^^. Thanks again for the amazing extension!

**Comment by Rurik19** [comment]
@ThibaudDauce  what was a keyboard shortcrt for ff-ext?

**Comment by ThibaudDauce** [comment]
The keyboard shortcut was Ctrl + Alt + s by default I think.

I never used it :-) But some users did ^^

**Comment by Rurik19** [comment]
In chrome 
> Combinations that involve Ctrl+Alt are not permitted

Let it be just Alt+w
In webextensions shortcut to execute browser action will works from v52 - I'v checked it with FF nighty.
For now it seems impossible to execute browser action from background. Correct me if I am not right.

**Comment by ThibaudDauce** [comment]
What do you mean by "from background"?
I'm not an expert in WebExtensions… But if Alt + w is working, I think it's fine?

**Comment by Rurik19** [comment]
At the moment, webextensions doesn't support "_execute_browser_action" key in manifest.json in the main branch, only since v52, which is nightly. It only can send command to background script, who cannot (at least a day of googling didn't help me) open popup window from inside

**Comment by ThibaudDauce** [comment]
It's the same for Firefox, it'll work with Firefox 52 https://bugzilla.mozilla.org/show_bug.cgi?id=1246034

**Comment by Rurik19** [comment]
@ThibaudDauce webextensions = Firefox for me :-)

**Comment by ThibaudDauce** [comment]
Haha :-)
For me, WebExtensions is a Chrome product implemented in other browsers ^^

**Comment by Rurik19** [comment]
done with #22
