### ISSUE TITLE
Wallabagger popup has a few problems

### ISSUE THREAD

**Issue by Mistress-Anna** [wallabag/wallabagger#131]
1. When wallabagger is not configured at all and thus unauthenticated, there's a label "connecting to API" or something like that, which doesn't say anything about missing configuration
2. The popup seems way too small for what it contains, see attached screenshot
3. The proposed choices for deletion are contradicting themselves ("yes, delete" vs "no, delete"), see attached screenshot

![wallabagger](https://user-images.githubusercontent.com/11899334/36758951-bf9818cc-1c0d-11e8-94b5-dba21b56b013.png)

**Comment by Rurik19** [comment]
Just checked - the 2 and 3 is OK in currernt version 1.7
![image](https://user-images.githubusercontent.com/1955806/58326083-35aec480-7e45-11e9-8535-37655cf72a9a.png)
the 1. I just made in dev branch, will be available in next release
![image](https://user-images.githubusercontent.com/1955806/58326217-9b02b580-7e45-11e9-95e0-03ba28f2a69d.png)
