### ISSUE TITLE
Saving the page to wallabag…

### ISSUE THREAD

**Issue by STaRDoGG** [wallabag/wallabagger#132]
I just installed the latest 1.4.5 in Chrome and according to the options page, all of my credentials are entered properly, and connecting, however, when I click the button to save a page, I see the usual popup, enter my tags, etc., but beyond that nothing ever happens. It just shows "Saving the page to wallabag…" indefinitely at the bottom of the dialog. Similarly, when I click the popup to go to the article's wallaby page, I just get the popup shown on a chrome extension page, with "Loading wallabag API…" shown indefinitely,

Nothing ever actually gets saved to my WallaBag installation.

I'm currently running Chrome Version 65.0.3325.181 (Official Build) (64-bit)

Any idea what's wrong?

Update:
I just tested the same version of the Firefox extension on CyberFox 52.7.2 (64-bit), with the exact same result.

**Comment by frafra** [comment]
Same issue here with Firefox 61.

**Comment by frafra** [comment]
Fixed. The extension has to be configured as an external client using Wallabag APIs.

**Comment by tuxmouraille** [comment]
Hello,
Save issue with Firefox 61.0.1 64bits on Windows 10, but works with Firefox ESR 60 64bits.

**Comment by Simounet** [comment]
Hi,
Can you try this and give the result to us please?

- enable the debug mode into the wallabagger settings
- go to about:debugging#addons
- check in Enable add-on debugging
- click on wallabag debug link
- click on ok to accept incoming connections
- add some page through the context-menu
- give us the entries on the console tab of the new window opened

**Comment by tuxmouraille** [comment]
Hi,
Sorry. I downgrade to Firefox ESR, then I could take a token. Next I upgraded to Firefox 61.0.1 again and now I can every time take a token.
My old Firefox 61.0.1 was auto-updated by Firefox from 61. The current 61.0.1 was install from fresh installer.
I'm trying to reproduce.

**Comment by tuxmouraille** [comment]
Hello,
I can't try to add some page because I can't configure wallabager to obtain a token.
I tried, and it works with Firefox ESR 60 en Nigthly 62 but not with 61.0.1, didn't tray with 61.
Then, I have downgraded Firefox to ESR 60.

**Comment by Simounet** [comment]
Usually, the steps on my previous comment should give you error even if you can't add links.

**Comment by tuxmouraille** [comment]
Hello,
Here with the errors in console, with Firefox 62 b15 64bits on Windows

```
Could not map contract ID '@mozilla.org/widget/printdialog-service;1' to CID {06beec76-a183-4d9f-85dd-085f26da565a} because no implementation of the CID is registered.
Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered. components.manifest:165
L’utilisation d’XMLHttpRequest de façon synchrone sur le fil d’exécution principal est obsolète à cause de son impact négatif sur la navigation de l’utilisateur final. Consulter http://xhr.spec.whatwg.org/ pour plus d’informations. util.js:40:2
Erreur d’analyse XML : erreur de syntaxe
Emplacement : moz-extension://f55820fe-e653-40cf-808d-4dd14dd289e0/rules/default.rulesets
Numéro de ligne 1, Colonne 1 : default.rulesets:1:1
Erreur d’analyse XML : aucun élément trouvé
Emplacement : moz-extension://f55820fe-e653-40cf-808d-4dd14dd289e0/_generated_background_page.html
Numéro de ligne 1, Colonne 1 : _generated_background_page.html:1:1
[Afficher/Masquer les détails du message.] Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:13 
```

**Comment by mvhulten** [comment]
I have the same issue with wallabagger 1.7.0 on Firefox 69.0.2.

**Comment by Simounet** [comment]
Are you still encountering this issue with the last wallabag and wallabagger versions?

**Comment by STaRDoGG** [comment]
> Are you still encountering this issue with the last wallabag and wallabagger versions?

Everything is a-ok here now. *thumbs up*

**Comment by Simounet** [comment]
Good to know. Stay safe and good evening!
