### ISSUE TITLE
Do not encode HTML entities in content sent to the API

### ISSUE THREAD

**Issue by flozz** [wallabag/wallabagger#135]
Hello,

When I edit a title or tags through Wallabagger, it encode HTML entities before sending them to the API. This causes Wallabag to display the encoded entities in the page. Example with title=`test " ' " '`:

![capture d ecran de 2018-04-20 13-46-20](https://user-images.githubusercontent.com/971438/39049668-b1b5964a-44a2-11e8-84fb-c3df78816894.png)

When I edit the title or the tags from Wallabag, I have no issue:

![capture d ecran de 2018-04-20 13-47-52](https://user-images.githubusercontent.com/971438/39049682-c921bdf4-44a2-11e8-889c-3c03b1bed413.png)

Also, when adding a tag containing a character that will be encoded, it is displayed twice (encoded and unencoded) until the popup is closed and opened again:

![capture d ecran de 2018-04-20 13-50-10](https://user-images.githubusercontent.com/971438/39049706-e146e74c-44a2-11e8-86be-efe842a00a6a.png)

* I wonder if there is a reason for encoding the HTML entities (old Wallabag versions expected this maybe)?
* Do you think we can remove this encoding?

**Comment by flozz** [comment]
I made the changes for myself to make tests: https://github.com/flozz/wallabagger/commit/1204a4e706d25ce7e7629289d0e369967e247d9e 

I can PR it if your are interested :)

**Comment by flozz** [comment]
You are right, I have the issue on the Wallabag 2.3.2 that is installed on my server, but I have no issue if I try this on Wallabag master. Probably this commit fixes this → https://github.com/wallabag/wallabag/commit/4d9128ded96bb70b7bda964870ba3e279832dd9b :)

**Comment by Simounet** [comment]
I think so. Can when close this issue and the associated PR?

**Comment by flozz** [comment]
Yes as it is not useful anymore :)

**Comment by Simounet** [comment]
Thanks and sorry about the late reply.
