### ISSUE TITLE
mass add, edit and delete tags to post

### ISSUE THREAD

**Issue by ofit** [wallabag/wallabagger#137]
Hello. Please add option to mass add, edit, delete tags to post. Because if i want add or delete tag linux for 5 post need edit every post manually. Thanks

**Comment by Rurik19** [comment]
Hi! I think you mean wallabag itself, not browser extension wallabagger? You should move this issue to [wallabag/wallabag](https://github.com/wallabag/wallabag) project.

**Comment by ofit** [comment]
You are right. sorry
