### ISSUE TITLE
Asks for user/pass

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabagger#138]
Hi

I use it on FF 56 (waterfox). Everytime I try to add an article via shortcut or the icon it keeps bringing the popup window with empty creds, and it says connection is impossible. 

The thing is that I have already provided the Client ID and the Secret key to addon settings. So why ask for user and pass? 

Also it does not remember the user and pass anyways.

I am using  wallabag-release-2.3.2 On Debian.

thanks

**Comment by Rurik19** [comment]
Hi! The wallabagger doesn't have any windows to enter creds. Is it like browser window? Does  your wallabag installation have additional basic http authentication?

**Comment by Rurik19** [comment]
Please take screenshot of that window
