### ISSUE TITLE
Token Not Granted

### ISSUE THREAD

**Issue by sinqbad** [wallabag/wallabagger#140]
Wallabag is installed on my shared host site installed using on cpanel using softaculous. In wallabag URL I put v2.wallabag.it or v2.wallabag.org and the wallabag url is checked ok. When I add the tokens and login my token isn't granted. 

When I put in my shared hosting url then Wallabag URL is checked unavailable.

I've followed the instructions for install so I don't know what's going wrong.

**Comment by Simounet** [comment]
Hello,
Can you follow these step and give the result to us:

- enable the debug mode into the wallabagger settings
- go to about:debugging#addons
- check in Enable add-on debugging
- click on wallabag debug link
- click on ok to accept incoming connections
- add some page through the context-menu
- give us the entries on the console tab of the new window opened

**Comment by U039b** [comment]
Hi!
Since few weeks Wallabagger 1.4.5 Firefox extension stop working. I have tested the same version of the extension on Chromium with the same settings and the extension works well. Tested on the same computer with the same Internet connection, same Wallabag credentials, *etc*. When I say "stop working" I mean the extension was not able to connect to my Wallabag server. 

When I click on "Get token" the POST request returns 
```
{"error":"invalid_client","error_description":"The client credentials are invalid"}
```

Any idea?

**Comment by Simounet** [comment]
Hi @U039b ,
Can you try it on a fresh Firefox profile? It could be an extension or any other custom parameter that stops the extension to work as expected.

**Comment by U039b** [comment]
Wallabagger works fine on a fresh profile.

**Comment by Simounet** [comment]
You can try to disable your addon one by one. Do you have umatrix or any other extension able to block requests?

**Comment by U039b** [comment]
I have 2 extensions able to block requests but auth POST request is correctly sent to my Wallabag server but returns 
```
{"error":"invalid_client","error_description":"The client credentials are invalid"}
```

**Comment by U039b** [comment]
Disabling these extensions does not fix the problem.

**Comment by Simounet** [comment]
Can you try to reset the extension and fill in the information one more time?

**Comment by U039b** [comment]
Even after uninstalling/reinstalling the extension or a parameters reset, the problem is not solved :-(

**Comment by Simounet** [comment]
Did you tried to disable all your extensions?

**Comment by U039b** [comment]
Yes I did but did not solved the problem :-(

**Comment by Simounet** [comment]
I'm really sorry but I'm kind of short here. If it's not your extension nor your credentials, I don't know. 
If you follow my debug processing from the second post of this topic, can you see the request and look at your sent credentials? (don't know if you're used to debug tools)
I can try to help you through IRC or Gitter. Just let me know which tool you prefer and when we can meet.

**Comment by Simounet** [comment]
I'm closing this old issue but feel free to reopen it if it's still a thing for you.
