### ISSUE TITLE
French translation issue

### ISSUE THREAD

**Issue by welcoMattic** [wallabag/wallabagger#141]
Firefox version, installed 2 days ago

![capture d ecran 2018-06-05 a 11 00 27](https://user-images.githubusercontent.com/773875/40966222-33a4a976-68b0-11e8-89df-625a5d6a945c.png)

The "No" message should be "Non, le conserver" ;)

**Comment by Simounet** [comment]
Fixed with v1.5.0 . Thanks for this info.
