### ISSUE TITLE
Does wallabagger work?

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabagger#146]
_From @GiganteX on July 3, 2018 21:7_

I installed the Wallabagger addon for Chrome. Got a button. Press it, a dialog opens with the text "Loading wallabag API..." or 

The options dialog has a Check URL button. I press it, nothing happens. "Wallabag URL checked" state is "Not checked".

Wallabag API token: Expired.

There's not much else to do...

??

_Copied from original issue: wallabag/wallabag#3681_

**Comment by j0k3r** [comment]
_From @GiganteX on July 3, 2018 21:29_

It worked fine on my own wallabag server though, so that's good.

**Comment by j0k3r** [comment]
_From @Simounet on July 11, 2018 18:21_

Sorry but I don't get your last reply. Can we close this issue? If not, can you go to the wallabagger project (https://github.com/wallabag/wallabagger/issues) to open an issue please?

**Comment by j605** [comment]
I am having the same issue. Is there any way to debug it? I am using the service at wallabag.it

**Comment by j605** [comment]
```json
postMessage: {"response":"setup-save","data":{"Url":"http://v2.wallabag.org","ApiVersion":"2.1.5","ClientId":null,"ClientSecret":null,"UserLogin":null,"UserPassword":null,"ApiToken":null,"RefreshToken":null,"ExpireDate":0,"isTokenExpired":true,"AllowSpaceInTags":false,"AllowExistCheck":false,"Debug":true}}
```
Ticking https makes the check URL not work at all on https://v2.wallabag.org. Setting the parameters in http version doesn't work and it just says token expired. I tried to save a page like you said and got
```json
postMessage: {"response":"setup-gettoken","data":{"Url":"http://v2.wallabag.org","ApiVersion":"2.1.5","ClientId":"clientidxxxxxxxxx","ClientSecret":"clientsecretxxxxxxxxxxxxxxxxxx","UserLogin":"j605","UserPassword":"password","ApiToken":null,"RefreshToken":null,"ExpireDate":0,"isTokenExpired":true,"AllowSpaceInTags":false,"AllowExistCheck":false,"Debug":true},"result":false}

postMessage: {"response":"setup","data":{"Url":"http://v2.wallabag.org","ApiVersion":"2.1.5","ClientId":"clientidxxxxxxxxx","ClientSecret":"clientsecretxxxxxxxxxxxxxxxxxx","UserLogin":"j605","UserPassword":"password","ApiToken":null,"RefreshToken":null,"ExpireDate":0,"isTokenExpired":true,"AllowSpaceInTags":false,"AllowExistCheck":false,"Debug":true}}
```

**Comment by Simounet** [comment]
Hi @j605 ,
Which service of wallabag are you using? https://framabag.org/login or https://app.wallabag.it/login ?

**Comment by j605** [comment]
https://app.wallabag.it/login

**Comment by Simounet** [comment]
Ok so you have to use `https://app.wallabag.it` into wallabagger URL, not `https://v2.wallabag.org`.

**Comment by j605** [comment]
Thanks! Setting to that URL worked. Do you think the [documentation](https://wallabag.org/en/news/wallabagger-howto) needs to reflect that or mention that v2 URL should not be used? Mainly this image ![](https://wallabag.org/images/7/e/c/0/1/7ec015a3843cd782de2bfa00b328a5632719956c-opt-url.png)

**Comment by Simounet** [comment]
You're right. We will update that and make it more explicit.

**Comment by vhmaheshp** [comment]
Hi everyone, it was the issue with URL.

{{domain}}/web

{{domain}} is your domain URL!

If it works give it a thumbs up so that it can help others.
