### ISSUE TITLE
Wallabagger won't validate url in Chrome

### ISSUE THREAD

**Issue by ahelton** [wallabag/wallabagger#148]
Hi,

I installed the Wallabagger extension today in Chrome. I have my Wallabag installation hosted on my A2 shared hosting plan. Whenever I put in the url (without the https) and click the 'check url' button nothing happens except that the text box outlines itself in red. I assume this means it can't properly validate the url, but I don't know why as I just copied and pasted it from the url bar in Chrome. Any ideas?
![wallabagurl](https://user-images.githubusercontent.com/7684997/45124868-966c6480-b131-11e8-9151-f0eb90958d2c.png)

**Comment by Rurik19** [comment]
Hi! go via browser address bar:   https://yourwallabagurl/api/version
Does it work? It is exactly the same thing "Check URL" button does.

**Comment by ahelton** [comment]
No, I get a 404 error. If I just go to my url it pulls up the wallabag login screen just fine, but when I insert my url with the '/api/version' it gives me the 404. Any clue what might be the problem?

**Comment by ahelton** [comment]
Good news. I got it to work. I was putting in my url like this: mysubdomain.mydomain.com/web/login (I also tried: mysubdomain.mydomain.com). Neither of those worked, but I just tried on a whim: mysubdomain.mydomain/web and it works perfectly.

**Comment by Simounet** [comment]
You didn't have install wallabag correctly. You shouldn't use /web as a path but a vhost pointing to the web folder as root. If you need help to do it, you can open an issue on the wallabag repository: https://github.com/wallabag/wallabag .
Have a nice day.

**Comment by ahelton** [comment]
I installed via Softaculous, so I went with whatever default installation procedure they use. Thanks for the tip, however. Maybe I should contact them?

**Comment by Rurik19** [comment]
Maybe

**Comment by Danie10** [comment]
Thanks this solved my problem too so its not sorted out by Softaculous. Adding the /web to the URL worked perfectly.
