### ISSUE TITLE
Cannot check URL

### ISSUE THREAD

**Issue by kmlucy** [wallabag/wallabagger#153]
When I try to check URL, I get this error in my NGINX logs:
```
172.18.0.15 - - [06/Dec/2018:17:44:20 -0500] "OPTIONS /api/version HTTP/1.1" 400 63 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
```

I can access /api/version with a GET request:
```
172.18.0.15 - - [06/Dec/2018:17:39:15 -0500] "GET /api/version HTTP/1.1" 200 38 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
```
With a result of:
```
"2.3.4"
```

I'm using the Docker container to host Wallabag.

**Comment by kmlucy** [comment]
In Chrome? I don't believe so. I have a reverse proxy in front of Wallabag.

**Comment by kmlucy** [comment]
Is there a way I can help debug this?

**Comment by kmlucy** [comment]
Solved. It was this option:
![image](https://user-images.githubusercontent.com/13952475/50033636-4ff79300-ffc7-11e8-8685-501d5ba99681.png)

When set to `On click`, it causes the OPTIONS call. If left on `On all sites` it works as designed.

**Comment by Rurik19** [comment]
**kmlucy** where can I find this setting?

**Comment by kmlucy** [comment]
@Rurik19 Right click on the Wallabagger icon and click 'Manage extensions'. It's about midway down the page under 'Permissions'.
