### ISSUE TITLE
Tagging not working

### ISSUE THREAD

**Issue by huegelc** [wallabag/wallabagger#154]
Wallabagger:  1.5.0
Wallabag API: 2.3.4
Firefox: 63.0.3

Issue: page is saved in wallabag without tags

![screenshot 2018-12-07 at 10 31 03](https://user-images.githubusercontent.com/6955465/49639418-412f4000-fa0b-11e8-8389-29aaf604a88a.png)

![screenshot 2018-12-07 at 10 31 52](https://user-images.githubusercontent.com/6955465/49639483-6a4fd080-fa0b-11e8-894d-68d73b61c930.png)

**Comment by Simounet** [comment]
Hi,
You can try this before trying to add some tags:
- enable the debug mode into the wallabagger settings
- go to about:debugging#addons
- check in Enable add-on debugging
- click on wallabag debug link
- click on ok to accept incoming connections
- add some page through the context-menu
- give us the entries on the console tab of the new window opened

**Comment by huegelc** [comment]
Hi,

here you go
```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. popup.html
postMessage: {"response":"setup","data":{"Url":"https://pocket.example.com","ApiVersion":"2.3.4","ClientId":"1_5509rsr1q6g40gg8oo0oog0ogw0w48k4o800sgwco0wk4ookkk","ClientSecret":"**************","UserLogin":"pocket","UserPassword":"*************","ApiToken":"**************","RefreshToken":"*****************","ExpireDate":1544549481461,"isTokenExpired":false,"AllowSpaceInTags":false,"AllowExistCheck":true,"Debug":true}} background.js:186:23
postMessage: {"response":"tags","tags":[{"id":-1,"label":"test","slug":"test"}]} background.js:186:23
postMessage: {"response":"info","text":"Saving the page to wallabag…"} background.js:186:23
Security Error: Content at moz-extension://922264ce-dfc0-fd4c-9aed-ad8a13ab673a/ may not load data from blob:null/a418b189-338c-f847-b937-3605d3d1755e.
Loading failed for the <script> with source “blob:null/a418b189-338c-f847-b937-3605d3d1755e”. blank:1:1
```
Thanks

**Comment by Simounet** [comment]
Hi,
Sorry for the late reply. Did you change the url? It seems that you are using `https://pocket.example.com`.

**Comment by huegelc** [comment]
Hi,

yes sure, the original output contains the correct url.

**Comment by Simounet** [comment]
Are you sure that you filled in correctly the URL on the addon settings page? Witch wallabag's instance are you using?

**Comment by huegelc** [comment]
As I said, only the tags do not work, pages are saved fine. What do you mean by instance?

**Comment by Simounet** [comment]
app.wallabag.it? framabag?

**Comment by huegelc** [comment]
Wallabag 2.3.4 is self hosted

**Comment by Simounet** [comment]
Ok so `https://pocket.example.com` is not your real URL. Did you try with the latest version of wallabagger (v1.6.0)?

**Comment by huegelc** [comment]
yes, same issue.

**Comment by huegelc** [comment]
Ok, I´ve updated wallabag to 2.3.6 and now it works as expected.
Thanks for your time.
