### ISSUE TITLE
Does not save link

### ISSUE THREAD

**Issue by lwebzem** [wallabag/wallabagger#157]
I installed extension on Chrome and it looks fine : 

Checklist | State
-- | --
Wallabag URL checked | Ok
Wallabag API version | 2.3.5
Wallabag API token | Granted
Token expires in | 40 minutes

However when I click wallabag it   - the link is not saving, the icon turn red (or orange) for a second and nothing come in wallabag. But I am able save inside of wallabag or from python via API.
I have windows 10 OS and
Google Chrome is up to date
Version 71.0.3578.98 (Official Build) (64-bit)

Also I am seeing message: "Loading wallabag API…"   OR 
"Saving the page to wallabag…"   and it is stay forever
Can you suggest something why it is not saving?
Thanks.

**Comment by mort74** [comment]
I've got the same issue. However, sometimes it does save the link even though the icon turns orange/red - but if so, nothing but the link and the window title, i.e. no contents at all.
I also tried to update the token. Everything turn red, but I can't tell why, as the German translation takes too much space. I only see the labels of the Checklist, but the states are clipped off, and there's not even a way to select / copy them.

**Comment by Simounet** [comment]
Hello, can you try again with the latest version (1.6.0) please?

**Comment by mort74** [comment]
Only partial success... Getting the token at the options page now turns green, and the pages were saved fine including the contents - but the icon still turns red.

**Comment by Simounet** [comment]
Can you try wallabagger on a fresh profile? Maybe do you have an extension that is blocking content?

**Comment by michaelpjohnson** [comment]
I have this same issue. Which extensions would be blocking this? I have very few, but uBlock and Privacy Badger seem the most likely. I've whitelisted my domain in both however. I am happy to help debug this.

**Comment by michaelpjohnson** [comment]
Actually it saves the page, but it still turns red, so the call isn't
blocked.

**Comment by Simounet** [comment]
Sorry for the late reply. Is it still an issue?


- enable the debug mode into the wallabagger settings
- go to about:debugging#addons
- click on wallabagger inspect button
- add some page through the context-menu
- give us the entries on the console tab of the new window opened

**Comment by Simounet** [comment]
Closing this issue. Feel free to open it again if needed.
