### ISSUE TITLE
no warnings when saving not sucessfull

### ISSUE THREAD

**Issue by fredleger** [wallabag/wallabagger#158]
Updated my email on framabag and saved articles for more than 2 weeks without noticing there were failling :(

it should display a warning or something in some way i think

**Comment by fredleger** [comment]
version 1.5.0 and wallabag api version 2.2.2

**Comment by Rurik19** [comment]
Looks weird. or like serious security issue on wallabag. I'll check that.

**Comment by Simounet** [comment]
Just checked this behavior, changing my password then using wallabagger without updating anything. I can see the error from the popin and the wallabagger red icon.
I'll close this issue. Feel free to open it again if needed.

**Comment by fredleger** [comment]
4 years later ... i switched from wallbag from something else. please feel free to dig it in the graveyard
