### ISSUE TITLE
tagging is slow

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabagger#16]
i am really happy there is a tagging interface! great progress. :)

unfortunately, it seems the tags are saved immediately, every time i hit "enter" or "space" (depending on the configuration). this can make the interface less responsive, especially if there are a lot of tags to enter - it can take up to one second to save each tag... while sometimes it's really fast, it really breaks my typing: i expected tags to be created in one shot, when i hit "enter" after typing in all the tags.

furthermore, tag search results cannot be selected with the keyboard. so sometimes i type part of a tag, and i need to move the mouse to the matching tag to select it, wait for it to be saved...

i feel this could be streamlined a lot!

thanks for this great plugin nevertheless. :)

**Comment by Rurik19** [comment]
I think that is some solutions for tagging improvements:
1) optimistic strategy in adding tag (not to wait while it really saves) +  it requires additional error handling
2) in react branch right arrow not adds tag immediately, but "select" it - next arrow - next found tag. It can be applied to v1 too, maybe with some config option
3) possibility to write a list separated with "," or ";" to add a bunch of tags

**Comment by anarcat** [comment]
i don't understand "optimistic" - do you mean "optimized"?

right now i always feel like i need to hit "enter" after entering the tags otherwise they are not saved. they are, of course, immediately saved right now, but maybe that could the way tags are finally entered?

regarding separating by "," or ";", i separate with spaces right now and it serves me well.

another speed optimization in the UI that could be useful would be to show the tagging interface while the article is being saved, in parallel. right now, i have to wait for the article to be saved before i do the tagging...

also, when i navigate to another tab, the save interface disappears, is that normal?

should i open separate bugs about the latter two issues?

**Comment by Rurik19** [comment]
"Optimistic strategy" means that we "hope" that async operation (saving tags here) will be ok and don't wait while it really saves and allow user to enter new tag right after beginning of saving previous.
- Tagging while saving is an interesting idea, it worth considering
- disappearing when you navigate another tab - it is normal, if there was "Saving article" info - article will be  saved.

And, yes, you should create separate issues about new feature request

**Comment by anarcat** [comment]
okay, i opened #28 and #27 for those, thanks for the feedback!
