### ISSUE TITLE
Two different browser Wallabagger installation in a same desktop

### ISSUE THREAD

**Issue by finnishbroccoli** [wallabag/wallabagger#161]
I did the following, first I installed wallabagger to a Brave browser and I got a token from app.wallabag.it

After that, I added Wallabagger to a Firefox. But the problem lies in a gui, it sort of tells that at the same time there is no connection to the app.wallabagger.it and add-on setup fails. But in reality, add-on recognizes Brave's token and accepts it.
The user interface should tell a user that token already exists and everything is ok.

**Comment by witecat** [comment]
Hi, I have a similar issue.
Installed Wallabagger extension for Firefox and Chrome. Chrome works fine, Firefox doesn't seem to react at all to the "Get token" button press.
Nothing happens!
Spent an hour searching for answers or support alternatives, and ended up with nada. 
Really like the concept, but useless if I can't get it to work on FF, which is my main browser

**Comment by Simounet** [comment]
Hi,
Do you have any extension that can block wallabagger? Can you try on a fresh profile?
At least, can you follow these steps and give me the result please?
- enable the debug mode into the wallabagger settings
- go to about:debugging#addons
- check in Enable add-on debugging
- click on wallabag debug link
- click on ok to accept incoming connections
- add some page through the context-menu
- give us the entries on the console tab of the new window opened

**Comment by Rurik19** [comment]
Also update to v 1.6, if not

**Comment by finnishbroccoli** [comment]
Hi,
Just to make sure that I don't do any unnecessary tests, I'd like to repeat that wallabagger UI is the problem, not the connection to app.wallabag.it
If I find a problem with connection, I just need to press get token and it is all set. Furhermore I think this odd behaviour which I tried to explain in my first post, appears only when setting wallabagger to the second browser the first time.
I have version 1.6.
I'd say no other extension causes any trouble.

**Comment by Simounet** [comment]
Sorry for the late reply. If I understood correctly, the issue here is about the set-up of wallabagger on two browsers. But I didn't understand the token issue. You don't have a return from wallabagger on the second browser that everything is ok?

**Comment by Simounet** [comment]
Closing this issue. Feel free to open it again if needed.
