### ISSUE TITLE
keywords, read status, text edit are not transmitted

### ISSUE THREAD

**Issue by lmjst** [wallabag/wallabagger#163]
I use wallabager firefox extension 1.6.0 and only the image and the title of the pages are saved, not the keywords, nor the read status nor the text change edit. 
I tried it with Firefox regular and Firefox quantum : same problem.

This is what the debug console says : 
could someone interprets it to give me a clue on what it means to find a solution.
Thanks

    sendRequestToSpecificTab moz-extension://e3ebc71b-b29d-41ce-b22e-8b063bdaff58/js/background.js:1
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:115
L’encodage de caractères du document HTML n’a pas été déclaré. Le document sera affiché avec des caractères incorrects pour certaines configurations de navigateur si le document contient des caractères en dehors de la plage US-ASCII. L’encodage de caractères de la page doit être déclaré dans le document ou dans le protocole de transfert. popup.html
postMessage: {"response":"setup","data":{"Url":"https://walla.me.fr/dir/web","ApiVersion":"2.3.7","ClientId":"1_msms0s04g0oocg4o","ClientSecret":"3yhsrs64d","UserLogin":"me","UserPassword":"e79xxx","ApiToken":"MzMyYWQx","RefreshToken":"Mjg4OGU5OGU2ZMDg4O","ExpireDate":1557695617323,"isTokenExpired":false,"AllowSpaceInTags":true,"AllowExistCheck":false,"Debug":true}} background.js:186:23
postMessage: {"response":"tags","tags":[{"id":-1,"label":"http","slug":"http"}]} background.js:186:23
postMessage: {"response":"info","text":"Enregistrement de la page dans wallabag…"} background.js:186:23
postMessage: {"response":"article","article":{"id":34,"is_starred":0,"is_archived":0,"title":"Les fantômes suisses des époux Balkany","url":"https://www.letemps.ch/monde/fantomes-suisses-epoux-balkany","tags":[],"domain_name":"www.letemps.ch","preview_picture":"https://assets.letemps.ch/sites/default/files/styles/share/public/media/2019/05/12/file75blhxhludt7xs3vmbi.jpg.jpeg?itok=IzOP1UNh"}} background.js:186:23
Error: Failed to update article https://walla.me.fr/dir/web/api/entries/34.json
                NetworkError when attempting to fetch resource. wallabag-api.js:136:23
Error: Failed to update article https://walla.me.fr/dir/web/api/entries/34.json
                NetworkError when attempting to fetch resource. wallabag-api.js:136:23
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1

**Comment by lmjst** [comment]
So I guess it's my fault since no one else seems to have this issue

**Comment by Simounet** [comment]
Sorry for the late reply. Do you have any extension that can block the request? Can you try with a fresh profile?

**Comment by lmjst** [comment]
Hi, just tried on Chromium with no other extension than Wallabagger in use and the result is the same : No keyword is saved.

**Comment by Simounet** [comment]
Can you give to us your wallabag version, please? Can you look at your server logs?

**Comment by Rurik19** [comment]
Don't you have any other security program like firewall/anti-virus/adblocker enabled?

**Comment by lmjst** [comment]
I've disabled the adblocker, private browsing, enabled cookies..still  no success whether Firefox 60.8.0esr, Firefox stable or Chromium Version 75.0.3770.142 (Build officiel)

**Comment by Simounet** [comment]
Hi @lmjst ,
Are you still encountering this issue or can I close it?

**Comment by lmjst** [comment]
Hello,
I've moved from Wallabag to Joplin, for the moment, so you can close this one I guess.
Thanks
