### ISSUE TITLE
Compatibility with Wallabag v2.3.8?

### ISSUE THREAD

**Issue by virtadpt** [wallabag/wallabagger#165]
Has anyone reported compatibility problems with Wallabag v2.3.8, by chance?

**Comment by Simounet** [comment]
I'm using it right now with 2.3.8 without any issue. What's the problem?

**Comment by virtadpt** [comment]
Trying to save anything to my Wallabag install has resulted in 401 errors in the server logs and red no-go W icons for Wallabagger on every site I've tried it on.  I tested the API tokens I use with Wallabagger at the command line with cURL and they work.

**Comment by Simounet** [comment]
Which browser and browser version are you using? Do you have any extension that can intercept the request? Can you try with a fresh profile?

**Comment by virtadpt** [comment]
I am using Chromium and Chrome on two separate laptops, both with Wallabagger v1.7.0.  I am also using Wallabag v2.2.1 for Android on two devices (one running Android 9 from Samsung, one running Android 6.0.1 from Google).  I do not use any extensions that intercept the requests.  I've tried with a fresh profile, same thing happens.

In Wallabagger, my URL checks out ("Ok"), it reads the API version correctly (2.3.8), and tokens can be granted as one would expect.

Whenever I try to store something with Wallabagger, I get the yellow "doing stuff" W icon, then the red "no-go" icon on Wallabagger.  If I tail my server logs I see the attempts get 401 errors from Apache.  However, if I use cURL and the Client ID and Secret from Wallabagger, Wallabag will generate a token for me.  However, the token does not seem to work when used in an "Authorization: Bearer ..." header, only as a parameter in the URL.

If it helps, when I was running Wallabag v2.3.3 everything was running smoothly.

I did a new install of Wallabag from Github last night (running HEAD), and I'm seeing the same problems.

Can you recommend a Chrome plugin or tool that I can use to collect more information?  I'm a back-end kind of guy (device drivers and daemons), not a webdev kind of guy, so any guidance would be very helpful.

**Comment by Simounet** [comment]
You can debug the extension with the dev mode from the extension page and look at the request made by wallabagger.

**Comment by virtadpt** [comment]
So noted.
That said, I set up a new install on a private server (not shared hosting) and that fixed all the problems.  I guess a few thousand stored articles in a database is a little too much for Dreamhost.
