### ISSUE TITLE
add shortcut to wallabag archive

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabagger#17]
i understand the main purpose of the plugin is to "bag" stuff, to save articles in the wallabag database. but i would also like to have a quick link to wallabag itself without having to save a page. maybe this could be available through the "right-click" action on the button? i know [the great suspender](https://github.com/deanoemcke/thegreatsuspender) is one extension that seems capable of adding such menu items, if you are looking for prior art...

**Comment by Rurik19** [comment]
Done with #23

**Comment by anarcat** [comment]
great, thanks!
