### ISSUE TITLE
allow deleting tags with the keyboard

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabagger#186]
As i type tags when saving a page, I often make typos, but i realize it after i hit "space" and the tag is "create" (as in, it appears in a little box with a `x` sign to delete it). Fixing mistakes then is difficult because it requires me to use the mouse and hunt for that `x` sign to delete the tag and type it again.

Ideally, the text field would keep behaving as a text field, even after the tag is created. That would mean that typing, say: `tagnamee`<kbd>SPACE</kbd><kbd>BACKSPACE</kbd><kbd>SPACE</kbd> would leave the tag `tagname` in place.

Alternatively, the <kbd>BACKSPACE</kbd> key could also delete the last tag if that's easier to implement. The general idea is to make it possible to delete or correct already typed tags using the keyboard.

Thanks!

PS: thanks for the new release! it looks slick! :)

**Comment by Simounet** [comment]
Hey @anarcat, I think you can use the keyboard with <kbd>SHIFT</kbd> + <kbd>TAB</kbd> to put the focus on the delete button then press <kbd>ENTER</kbd>. 
Is it ok for you?

**Comment by anarcat** [comment]
uh! that's kind of a neat hack... really hard to discover and lots of typing, but it does work... i'll see if it's enough to make me stop using the mouse. :)

**Comment by Simounet** [comment]
I understand it's hard to find alone but it's how keyboard navigation works. Plus, you have an option to enable spaces in tags then you have to use <kbd>ENTER</kbd> to validate tags.
I'm trying to help you AND avoiding to complicate casual behaviors. :p

**Comment by anarcat** [comment]
> I'm trying to help you AND avoiding to complicate casual behaviors. :p

yeah, i understand where you're coming from... i do like to use space to enter tags more quickly, and the idea of allowing <kbd>BACKSPACE</kdb> to work was in that direction as well...

**Comment by Rurik19** [comment]
Hi all! I like using keyboard navigation, and I think this ideas is good! am going to implement some ideas/

**Comment by Rurik19** [comment]
**anarcat** - check development branch = backspace returns value to input an delete last tag, left arrow with empty input select last tag, then left - right to select other tags and DEL to delete selected tag.

**Comment by Rurik19** [comment]
published with v1.10
