### ISSUE TITLE
Explain permissions change

### ISSUE THREAD

**Issue by zyphlar** [wallabag/wallabagger#194]
Previously, it seems Wallabagger (Firefox) only required info about browser tabs. Now it can "Access your data for all websites" which is scary. Can you explain why this change was made and why it's necessary?

**Comment by johnjameswhitman** [comment]
Did the extension break for you? I'm on Firefox 72.0.2 / Ubuntu 19.10 and it no longer works, but can't figure out if it's the browser or the extension causing issues.

**Comment by tcitworld** [comment]
@zyphlar Did you see https://github.com/wallabag/wallabagger/issues/191#issuecomment-580326012 ?

**Comment by Simounet** [comment]
I agree that we are getting to much permission. I found a lighter solution. I'm working on it right now.

**Comment by Simounet** [comment]
We released a new version with fewer permission needed. Available right now on Firefox and soon on Chrome. Have a nice day.
