### ISSUE TITLE
Extension logo is taking lot of space.

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabagger#196]
In firefox (at least) the Wallabag logo is taking a lot of place for no reason.
![Capture](https://user-images.githubusercontent.com/8579/74538064-abab0c80-4f3b-11ea-8c59-11f09b1c9fe6.PNG)
Perhaps there is a way to keep the logo but improve the looking of the widget

**Comment by tcitworld** [comment]
When a picture has been fetched by wallabag, the picture shows in place of the wallabag logo.

**Comment by Rurik19** [comment]
yeah, it is picture placeholder. and I see it should have more top margin :smile:

**Comment by Simounet** [comment]
This change with a smaller icon will be released in the [next version](https://github.com/wallabag/wallabagger/releases/tag/v1.11.0). You can look at #234 for the result. Have a nice day.
