### ISSUE TITLE
Logged out with latest update (Firefox)

### ISSUE THREAD

**Issue by Najrim** [wallabag/wallabagger#201]
The latest update caused me to be logged out and all information stored by the plugin seems to be gone. Not even the wallabag URL was left. Not sure if this was supposed to happen. #164 is still open, otherwise I would have expected it to have to do with that.

**Comment by Simounet** [comment]
Hello Najrim,
I encountered the same issue and I'm looking for a solution. I think it will be an issue this time but I want to be sure it won't happen again.

**Comment by Simounet** [comment]
I released a new version with a fix for that issue. I apologize for the inconvenience for users facing this issue in the mean time.
