### ISSUE TITLE
Permission check and API token not granted in Firefox

### ISSUE THREAD

**Issue by andyforceno** [wallabag/wallabagger#202]
I am suddenly unable to obtain an auth token with the Wallabagger Firefox extension. This began suddenly today when I tried to save an article. I tried setting up a new API client in the Wallabag web interface, but I can't obtain a token with that, either. Interestingly, this problem is only happening with Wallabagger. I can save article fine using the Android app with the same API credentials I've been using for a while. 

My nginx logs show: 
`"OPTIONS /oauth/v2/token HTTP/1.1" 400 43 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"`

I believe I'm using Wallabagger 1.10.3, that's what the manifest.json says, anyway. I'm using Wallabag 2.2.3, if that matters (I believe that is immaterial to this issue). Firefox 73.0.1 running on Manjaro Linux. 

This is from the firefox debug console when I try to obtain a new token in the Wallabagger preferences tab:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mydomain.com/oauth/v2/token.`

I haven't changed anything in nginx's config in a long, long time. Is this due to some change in Firefox? It seems like it. 

I saw the issue where #160 was suggested as a fix, but if I'm reading right, my version of Wallabagger should include that fix.

One thing I've noticed is when I enter my url and click Check URL, I am not prompted to allow the addon access to my data. I tried it in the latest version of Chrome and I get that right away. No issues with Wallabagger in Chrome. In Firefox, once I click Check URL, I do not get the fields to enter the client ID and secret, in fact those boxes disappear! I have to refresh the add-on tab to get them to show. I have the same issue in Firefox if I try to authenticate with Wallabagger in a private window. I have not tried a new profile.

In the "checklist" I have `Wallabag permission checked | Not checked` and of course API token is `not granted`. I have tried restarting FIrefox, reinstalling Wallabagger, and rebooting my PC. Nothing has worked so far. Certainly seems like something has changed in Firefox recently!

**Comment by Simounet** [comment]
Hi there,
I'm sorry to hear that. It seems weird that it didn't work on uninstall/reinstall. Do you have any blocking extensions that could break this? Can you try it on a fresh Firefox profile please?
Do you remember encountering the permission prompt to access to your wallabag domain?

**Comment by andyforceno** [comment]
I've never had permission issues when accessing my domain. I'll try a new profile and report back.

**Comment by andyforceno** [comment]
Same results with a new firefox profile, no addons enabled except Wallabagger. Here's what happens: I enter my address, click the Check URL button, and Firefox prompts me to grant permission, which I do. The "permission check status" changes to Granted, and then "API token" shows expired, but I never get fields to enter client_id and secret. I can't proceed past this. If I click Check URL again, the permission status changes to "Not checked" but nothing else happens. 

I'm still seeing 400 errors for `/api/version` in nginx's logs.

**Comment by Hodapp87** [comment]
Seeing the same on my own configuration across two separate Firefox installations that both were working previously. Nothing on the server has been changed. Chromium is fine.

**Comment by andyforceno** [comment]
I moved my Wallabag installation to my second server and have no problems with Wallabager in Firefox. It doesn't make sense to me.

**Comment by Simounet** [comment]
It might be an Nginx configuration issue. Can you give me the URL of the wallabag instance causing the issue. If you don't want to share it publicly, you can send me an email (wallabagger at simounet dot net).

**Comment by Hodapp87** [comment]
If I look at Wallabag logs, I see this when I hit 'Check URL' in Chrome:

```
172.18.0.1 - - [09/Mar/2020:12:05:14 +0000] "GET /api/version HTTP/1.0" 200 27 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"
```

And I see this when I do the same in Firefox:

```
172.18.0.1 - - [09/Mar/2020:12:05:30 +0000] "OPTIONS /api/version HTTP/1.0" 400 52 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
172.18.0.1 - - [09/Mar/2020:12:05:31 +0000] "OPTIONS /api/version HTTP/1.0" 400 52 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
```

so I'm not sure what explains that difference. My nginx config hasn't changed, and no software has been updated server-side in months.

**Comment by SyntrophicConsortium** [comment]
Firefox was just updated to v76 and this problem has come back again.

**Comment by gerhardbeck** [comment]
Is this problem solved? Experiencing the same problem. Yesterday it worked, not it doesn't Firefox 82.00 Ubuntu

**Comment by andyforceno** [comment]
I'm no longer experiencing it. I can't recall what I did, if anything, to resolve it. Have you tried generating new API token in Wallabag and using that?

**Comment by gerhardbeck** [comment]
That worked. Thanks.

**Comment by Simounet** [comment]
Glad to know you fixed it. I'm closing this issue. Fill free to reopen it if this problem appears again.
