### ISSUE TITLE
Trim fields upon save to avoid excess whitespace

### ISSUE THREAD

**Issue by BrookeDot** [wallabag/wallabagger#210]
I recently entered my `Client ID` and `Client secret` into the extension for Firefox but due to the copy and paste I had spaces in the beginning and end. 

It would be great is the spaces on either end got trimmed upon save (likely for all fields) but especially those where a copy and paste is common such as the Client tokens, user password, URL, etc.

**Comment by Simounet** [comment]
Excellent idea and it will be released in the [next version](https://github.com/wallabag/wallabagger/releases/tag/v1.11.0). Have a nice day.
