### ISSUE TITLE
Using Wallabagger with articles behind paywalls?

### ISSUE THREAD

**Issue by dorearendil** [wallabag/wallabagger#223]
Hi all,
I've started using Wallabagger in earnest, and it mostly works very nicely. Great work!

One thing that doesn't seem to be working for me at the moment is saving news articles that I must access behind a paywall. Particularly one site, French news media Mediapart.fr: although I have an account and can read all articles once I log in, Wallabagger only seems able to save the article preview (where it says "subscribe now to see the full article!"), even when I try saving an article after logging in of course.

Any tweaks/workarounds I might try? Mediapart is unfortunately one of my favourite news sources...

Cheers,
D-

**Comment by Simounet** [comment]
Hi there,
Sorry for the late reply. You can't grab articles from Mediapart at all? Did you fill in the credentials on `/site-credentials/`?

**Comment by dorearendil** [comment]
> Hi there,
> Sorry for the late reply. You can't grab articles from Mediapart at all? Did you fill in the credentials on `/site-credentials/`?

Thanks for your reply. No, I cannot grab Mediapart articles, despite filling in my correct site credentials in my app.wallabag.it account section... Strange, as Mediapart is listed in the 'compatible websites' on [this page](https://doc.wallabag.org/en/user/articles/restricted.html)?

**Comment by Simounet** [comment]
I can confirm that it's working. Are you 100% sure to enter the credentials correctly? No extra spaces or stuff like that?

**Comment by dorearendil** [comment]
Oups! sorry for the late reply. I can confirm that on my end (Ubuntu 20.04 / Firefox, using app.wallabag.it), my correct Mediapart credentials saved in the Wallabag backend do not enable me to capture whole Mediapart articles - only the non-subscriber preview. :(

**Comment by Simounet** [comment]
Can you give the content of the following file `vendor/j0k3r/graby-site-config/mediapart.fr.txt` please?

**Comment by dorearendil** [comment]
> Can you give the content of the following file `vendor/j0k3r/graby-site-config/mediapart.fr.txt` please?

Hmm... I'm using the online version, app.wallabag.it , so I don't think I have access to that file?
I didn't install WB on my own server, if that's what you mean.

**Comment by Simounet** [comment]
Sorry, I didn't remember that you were using wallabag.it. I just checked and it's working as expected with the following url: https://www.mediapart.fr/journal/france/211120/paris-des-milliers-de-manifestants-pour-contrer-la-derive-liberticide-du-pouvoir .
Because it's not related to wallabagger but wallabag itself, you should open a ticket on https://github.com/wallabag/wallabag/issues and told them that it's on the wallabag.it version.

**Comment by Simounet** [comment]
Do your user or password contain extra special characters? You can mention me in the new issue. If I can help, I will.
