### ISSUE TITLE
Chrome Extension Port

### ISSUE THREAD

**Issue by carepack** [wallabag/wallabagger#241]
Since apple provides a way to port chrome extension to safari leads to the question is this in the pipe? Everything i red this should be easy for experienced people. I tried already with no luck - but im not a developer. This would be very handy in case someone would use safari mainly and wallabag. Thx for some information about this

**Comment by jandamm** [comment]
@carepack Have a look in this issue:
https://github.com/wallabag/wallabagger/issues/214

**Comment by Simounet** [comment]
Doing some cleaning here and doubloon with #214 .
