### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by SuperDarius-git** [wallabag/wallabagger#253]
Please help me. I am putting in the URL of my self hosted Wallabag service, but the extension keeps saying "Not Checked" and "Not Granted". Don't know what I am doing wrong. Please help. I am using a Chrome extension on Windows 10.

Thank you
Darius

**Comment by SuperDarius-git** [comment]
I omitted the /web - thank you...

**Comment by Simounet** [comment]
Hi @SuperDarius-git , sorry for the late reply. Is this issue still bothering you or can I close it?

**Comment by Simounet** [comment]
Perfect!
