### ISSUE TITLE
Saving a youtube link saves the consent link

### ISSUE THREAD

**Issue by zeorin** [wallabag/wallabagger#268]
When I save any YouTube link it actually saves a consent link instead:

![wallabag](https://user-images.githubusercontent.com/1187078/117495046-6fffc680-af75-11eb-8f10-ef987c8d0e25.png)

https://www.youtube.com/watch?v=yq_E3HquRJY is the link I was trying to save.
https://consent.youtube.com/ml?continue=https://www.youtube.com/watch?v=yq_E3HquRJY&gl=DE&hl=de&pc=yt&uxe=23983172&src=1 is the link it did save.

This is what it looks like in Wallabag:
![image](https://user-images.githubusercontent.com/1187078/117495342-c66d0500-af75-11eb-941a-8a6598245540.png)

Re-fetching the content in Wallabag seems to fix the issue, but I would like not to have to do this manually for every YouTube video.

Firefox 88.0.1 (64-bit), Linux
Wallabagger 1.10.3
Wallabag instance is https://app.wallabag.it/

I am not in Germany, I do not have a German locale set up on my computer, and I'm not using a VPN.

**Comment by koppa** [comment]
I observe the same behavior with wallabag Version: 2.3.8.

**Comment by RememberTheAir** [comment]
This looks like to be an issue when the server fetches the page content. I have this issue when saving youtube links from the website/app/API, but not with the Wallabagger extension: maybe the behavior changed lately, and the extension uses your "local" loaded page instead of having the server fetch it?

**Comment by koppa** [comment]
I'm using firefox too.
I think that the fetch is the problem, the link points to the correct youtube page not the consent page, see the following screenshot:
https://imgur.com/a/5XmZHvj

Any way I can help to debug this problem?

**Comment by koppa** [comment]
@zeorin Do you still experience the problem?
With wallabagger 1.13.0 I don't have this problem anymore
Wallabag still version: 2.3.8

**Comment by zeorin** [comment]
@koppa you are right, I don't have this issue on 1.13. I had not checked in a while.
