### ISSUE TITLE
moving to another tab dismisses the save dialog

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabagger#28]
it can sometimes take time to save a page if the server is overloaded, slow, or the connection has problems. i sometimes get distracted and move to another window or tab, but then the window is closed and all work is lost.

i was expecting the window to stay open and operations to continue there.

**Comment by Rurik19** [comment]
It seems that showing popup from background code is forbidden :( But with v1.4 saved articles will be cached, so clicking on icon or using hotkey brings popup up very fast and you will be able to set tags.
That will be ok about your problem?

**Comment by anarcat** [comment]
yes.

**Comment by Rurik19** [comment]
v1.4 released!
