### ISSUE TITLE
Extension isn't updating in Chrome Web Store

### ISSUE THREAD

**Issue by rakleed** [wallabag/wallabagger#291]
The extension is not updated in the [Chrome Web Store](https://chrome.google.com/webstore/detail/wallabagger/gbmgphmejlcoihgedabhgjdkcahacjlj). At the moment, there is version 1.10.4 from March 3, 2020, although the current version is 1.13.0 from May 26, 2021.

**Comment by MoryCorp** [comment]
Check this : https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/
Downlaod latest source code from releases and uses it

**Comment by rakleed** [comment]
@Simounet @nicosomb @j0k3r please take a look

**Comment by j0k3r** [comment]
I've no idea how to update the extension on the store.

**Comment by Simounet** [comment]
I looked at it a few months ago and I think that @Rurik19 is the only one that can do that.

**Comment by nicosomb** [comment]
@Rurik19 Hello! Could you please have a look on this issue and authorize @Simounet, @j0k3r, @tcitworld and I to update the extension.

**Comment by Rurik19** [comment]
Hi all! Long time to see! Take me a day or two, and I update the extention or authorize somebody to do it!

**Comment by Rurik19** [comment]
Done, It is awaiting for approving now.

**Comment by nicosomb** [comment]
Hello @Rurik19! I hope you're fine. Thank you for your work 😊 Could you contact @Simounet to see how we can improve our release system for this extension?

**Comment by Rurik19** [comment]
Ok, it v1.14 in the store now

**Comment by nicosomb** [comment]
Thank you @Rurik19 !

**Comment by j0k3r** [comment]
@Rurik19 what do you need to add more maintainer to the Chrome Web Store?
Meanwhile, I'm closing that issue as the store is up to date.

**Comment by j0k3r** [comment]
👋🏼 @Rurik19

**Comment by Rurik19** [comment]
@j0k3r There are several maintainers in the Chrome Web Store. In fact, the last version = 1.15 was published not by me. (by @Simounet ?). There was security question from the store, they are solved now.
![изображение](https://user-images.githubusercontent.com/1955806/217245750-b00fd63a-5586-4f51-9bb3-2113e24d1fd3.png)

**Comment by nicosomb** [comment]
@Rurik19 oh you're right 😬
