### ISSUE TITLE
Move this project into the wallabag organization?

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabagger#3]
Hello @Rurik19! 

Do you want to integrate our team and move this project to the wallabag organization please? 

Nicolas

**Comment by Rurik19** [comment]
Oui,bien sûr, ça sera intéressant!

**Comment by nicosomb** [comment]
I added you in our organization.

**Comment by nicosomb** [comment]
Any news?

**Comment by Rurik19** [comment]
News:
1) v1.1 published
2) I am writing docs, honesty :) already wrote about installation!
3) publishing ext in opera browser - in process
4) about v2  - basic functionality is ready, options page in progress

**Comment by nicosomb** [comment]
any news to migrate your repo in our great team?

**Comment by Rurik19** [comment]
I am ready, just do not know how to do that.
Settings -> transfer  is right thing?

**Comment by nicosomb** [comment]
Yes.

**Comment by Rurik19** [comment]
Done!

**Comment by nicosomb** [comment]
👍

**Comment by anarcat** [comment]
it looks like, while the project was transfered, the [app store page](https://chrome.google.com/webstore/detail/wallabagger/gbmgphmejlcoihgedabhgjdkcahacjlj) still points to [the fork](https://github.com/Rurik19/wallabagger), which has [fixes not present here](https://github.com/wallabag/wallabagger/compare/master...Rurik19:master).

it would be nice to be able to report issues against the project - right now people may think they can't because they won't find the tiny link to the fork, if they are unfamiliar with github. :)

**Comment by nicosomb** [comment]
You're right. it's a job for @Rurik19 ;-)

**Comment by Rurik19** [comment]
Link is fixed.  @anarcat  What  fixes doesn't present where?

**Comment by anarcat** [comment]
@Rurik19 there are 3 commits on your fork not present here: https://github.com/wallabag/wallabagger/compare/master...Rurik19:master

**Comment by Rurik19** [comment]
@anarcat it prepared yesterday for firefox store.  PR - today

**Comment by Rurik19** [comment]
Added links in opera store too

**Comment by nicosomb** [comment]
https://addons.opera.com/en/extensions/details/wallabagger/?display=en nice 

Can you add this link on our website please?

**Comment by Rurik19** [comment]
I've done that deja, but all changes there must be approved - I think in a day or two

**Comment by nicosomb** [comment]
I mean "on our website wallabag.org https://www.wallabag.org/pages/download-wallabag.html"

**Comment by Rurik19** [comment]
add another box for Opera?

**Comment by nicosomb** [comment]
Yes.

**Comment by Rurik19** [comment]
ok

**Comment by Rurik19** [comment]
@nicosomb  download.md doesn't correspond with site - there aren't a box for  "iPhone for wallabag v2 only"

**Comment by nicosomb** [comment]
after chrome

**Comment by Rurik19** [comment]
@nicosomb  PR: https://github.com/wallabag/wallabag.org/pull/48
