### ISSUE TITLE
Traditional Chinese Support

### ISSUE THREAD

**Issue by extremelyonline** [wallabag/wallabagger#307]
Hi,

I noticed that the extension doesn't support Traditional Chinese. This can be easily done with a simple translation. Would you consider adding this feature? Let me know if I can contribute in any way. Thank you.

**Comment by Simounet** [comment]
Hi there,
Can you confirm this is still an issue please? Seems like there is one: https://github.com/wallabag/wallabagger/blob/master/wallabagger/_locales/zh/messages.json.
Have a nice day.
