### ISSUE TITLE
Fetch content directly from the browser for each website

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabagger#309]
Hi there!

Thank you so much @agallou for your work. 

Is that possible to remove the configuration part of your work and fetch content directly from the browser for each website? 

Nicolas

**Comment by agallou** [comment]
In my mind this would be a BC break (the configuration were here to opt-in on this functionality).

Some behaviors would break.
For example : if I'm on mediapart (supported with the site credentials, and configured on my account), but not connected, currently I can add it to wallabag with the extension and the full article will be on Wallabag, available to read it later.

If we remove the configuration part, this will stop working.

Do you still want to remove the configuration part ? (if that's the case I can prepare a pull request for that).

**Comment by nicosomb** [comment]
One point for the credentials part.

**Comment by lapineige** [comment]
Would it be possible to use Wallabag API to check if some credentials exist for a particular website/domain, and if not then directly retrieve browser content ?

**Comment by nicosomb** [comment]
@lapineige I also thought about this solution. But we need to work on wallabag API.

**Comment by Kdecherf** [comment]
Another way I would approach it is to add an action in this extension's menu to save the article by grabbing the content:

![2022-03-21-130537_2560x1440](https://user-images.githubusercontent.com/226063/159257709-30cf0bc5-1e03-4179-9e57-0fb1ff849589.png)

**Comment by Kdecherf** [comment]
(I'm not a big fan of making the extension always grab the content by removing the configuration btw, however we could put an opt-in configuration to do that)

**Comment by lapineige** [comment]
> Another way I would approach it is to add an action in this extension's menu to save the article by grabbing the content:
> 
> ![2022-03-21-130537_2560x1440](https://user-images.githubusercontent.com/226063/159257709-30cf0bc5-1e03-4179-9e57-0fb1ff849589.png)

Well if that is possible, I think that's the best way to do it, that's easier and as fast to do for both use case.

**Comment by biva** [comment]
Definitely! It would make it really usable by everybody because adding a line in the config is not easy for everyone. Congrats again for this feature!! Does it represent a lot of work? Happy to test if needed

**Comment by Kdecherf** [comment]
Can we consider this as a satisfying fix or workaround @nicosomb?

https://kdecherf.com/blog/2023/08/02/fetch-content-from-browser-on-demand-with-wallabagger/
