### ISSUE TITLE
Fetch content directly from browser: blocked by cookies

### ISSUE THREAD

**Issue by biva** [wallabag/wallabagger#314]
Hello,
Congrats @agallou for your work and this new feature. It worked well for me several times, but it didn't work for this URL: https://www.chaperonsetvous.fr/la-permanence-de-lobjet-3/
I added this line in the addon's settings, but wallabag retrieve only this:
> Panneau de gestion des cookies
En autorisant ces services tiers, vous acceptez le dépôt et la lecture de cookies et l'utilisation de technologies de suivi nécessaires à leur bon fonctionnement.
Préférences pour tous les services

Would you have any idea why it's not retrieving the page? 

This is behind a paywall, but I can share credentials in DM if needed.

**Comment by agallou** [comment]
The condition to see if the page must be fetch locally is here : https://github.com/wallabag/wallabagger/pull/300/files#diff-45a26550cb91696cb8ce6bab9815b6ed166a4b3901d68c64354d79887a171501R180-R190
The url is used for the comparison, but have you tried to only enter the protocol and domain ? (to add `https://www.chaperonsetvous.fr` in the configuration).
Also : dit you tried to reload the page after adding the configuration and add the page to wallabag ?

**Comment by biva** [comment]
Thanks @agallou for your feedback:
- I have tried both URL (see picture below)
![image](https://user-images.githubusercontent.com/9964305/163469245-68aab9a6-4556-4902-afb1-668a784f5441.png)
- I have tried to reload the page after adding the configuration
It doesn't work :(

**Comment by Simounet** [comment]
Hi @biva, only the second line should be needed. I can try to help you if you can share your credentials (change your pass before and after). contact at simounet dot net.

**Comment by biva** [comment]
Thank! Done @Simounet

**Comment by Simounet** [comment]
Well, I get it working. Are you using wallabag.it or a self-hosted instance?

**Comment by biva** [comment]
A self-hosted instance 2.4.3. It used to work at the  beginning with this site. Is it possible that some Firefox privacy add-ons are blocking something? 

Add-ons
Name 	Type 	Version 	Enabled 	ID
British English Dictionary (Marco Pinto)	dictionary	3.0.9	true	marcoagpinto@mail.telepac.pt
French spelling dictionary	dictionary	6.3.1webext	true	fr-dicollecte@dictionaries.addons.mozilla.org
German Dictionary	dictionary	2.0.6.1webext	true	de-DE@dictionaries.addons.mozilla.org
Spell checker for es-ES	dictionary	3.2.6	true	es-es@dictionaries.addons.mozilla.org
Amazon.co.uk	extension	1.1	true	amazon@search.mozilla.org
Automatic Dictionary	extension	3.0.1	true	automatic_dictionary_extension@jordi_beltran.net
Bing	extension	1.0	true	bing@search.mozilla.org
CardBook	extension	75.7	true	cardbook@vigneau.philippe
Chambers (UK)	extension	1.0	true	chambers-en-GB@search.mozilla.org
DuckDuckGo	extension	1.0	true	ddg@search.mozilla.org
Expression Search - NG	extension	3.1	true	expressionsearch@opto.one
Google	extension	1.0	true	google@search.mozilla.org
Previous Colors	extension	1.2	true	previous-colors@alkatrazstudio.net
Quicktext	extension	4.3	true	{8845E3B3-E8FB-40E2-95E9-EC40294818C4}
Quote Colors & Collapse	extension	3.2.7	true	quotecolors@thunderbird-mail.de
Remove Duplicate Messages	extension	0.5.2b4	true	{a300a000-5e21-4ee0-a115-9ec8f4eaa92b}
Shrunked Image Resizer	extension	5.0.4	true	shrunked@darktrojan.net
Signal Spam	extension	4.1.0	true	signal-spam@signal-spam.fr
Wikipedia (en)	extension	1.0	true	wikipedia@search.mozilla.org
Account Colors	extension	13.5	false	accountcolors@DW-dev
Auto Resize Image	extension	1.1.0	false	AutoResizeImage@gmail.com
Auto Save Drafts Folders	extension	1.0.0	false	asdf@d.lech
CompactHeader	extension	3.0.0beta5	false	{58D4392A-842E-11DE-B51A-C7B855D89593}
Expression Search / Google Mail UI	extension	1.4beta	false	{03EF8A6E-C972-488f-92FA-98ABC2C9F8B9}
Grammalecte [fr]	extension	2.1.1	false	French-GC-TB@grammalecte.net
Grammar Checker	extension	0.9	false	grammarchecker@codedgers.com
Mail Merge	extension	8.4.0	false	mailmerge@example.net
Thunderbird Conversations	extension	4.0.18	false	gconversation@xulforum.org

**Comment by Simounet** [comment]
Nope, it was missing a site config file. If you don't want to wait a release, you should get https://raw.githubusercontent.com/fivefilters/ftr-site-config/master/chaperonsetvous.fr.txt and put it inside this folder `vendor/j0k3r/graby-site-config/chaperonsetvous.fr.txt`. Hope this will help you.

**Comment by Simounet** [comment]
Hi @biva 
Can you share a screenshot of this issue? I can take another look if you want me to.

**Comment by biva** [comment]
Thanks for your support, I close this issue because it's not needed anymore. Thanks again!
