### ISSUE TITLE
Weblate translation contributions blocked

### ISSUE THREAD

**Issue by xmgz** [wallabag/wallabagger#315]
Please take care of this problem in hosted.weblate so we can contribute with translations

https://hosted.weblate.org/projects/wallabag/wallabagger/#alerts

**wallabagger** component has been blocked since many weeks/months (I've checked every other week).

There're similar problems, so blocked, in some other components of wallabag.

thank you.

**Comment by tcitworld** [comment]
Fixed, thanks for reporting.
