### ISSUE TITLE
Not capturing full page on Reddit

### ISSUE THREAD

**Issue by bilbags** [wallabag/wallabagger#326]
I'm running wallabagger 1.14.0 extension for Firefox and no matter where on the page I hit the wallabagger icon on the right-click context menu, it only captures the initial post. I have also tried selecting it in the middle of the page, the bottom, and tried hitting the extension button option as well at various places, to no avail. It always captures only the initial post and none of the comments. 

I also tested this with the latest Google Chrome extension and got the same result. 

Would love any pointers or advice! Thanks so much - I just installed wallabag on my Synology yesterday in a docker container and am enjoying it thus far. Still learning how to use all the features.

**Comment by Simounet** [comment]
Hi @bilbags wallabag only retrieve the main contain on purpose. You should get the same result adding the url directly from wallabag, don't you?
