### ISSUE TITLE
v.1.14.0 stuck on "Loading Wallabag API..."

### ISSUE THREAD

**Issue by itsthejb** [wallabag/wallabagger#328]
Hi,

I've been trying to use the latest v1.14.0, installed unpackaged, as this latest version isn't available on the Chrome store.

Unfortunately, trying to save a page seems not to work at all. The drop box will stick with:

<img width="269" alt="Screenshot 2022-10-19 at 16 24 51" src="https://user-images.githubusercontent.com/557391/196735489-02a80a00-388e-4ee2-bf07-fff903777b4d.png">

This is with verified account details (self-hosted). Using the Chrome store version from https://chrome.google.com/webstore/detail/wallabagger/gbmgphmejlcoihgedabhgjdkcahacjlj works just fine with the same details,.

Can anyone help?

Thanks in advance!

**Comment by Simounet** [comment]
Hi @itsthejb ,
Thanks for using wallabag and wallabager. I'm on it and I'll try to do my best to help you.

**Comment by itsthejb** [comment]
Thanks very much for the excellent software! Please let me know if I can do anything to help debug

**Comment by Simounet** [comment]
I found were the bug where introduced. I'm trying to make all of this work on Chrome too.

**Comment by Simounet** [comment]
Hi @itsthejb I'm sorry for the late reply. I thought I replied to you already. Can you try the master branch please?

**Comment by itsthejb** [comment]
Hi! Thanks for looking into this. Just checked - yes, it appears to be working!

**Comment by Simounet** [comment]
Good to know! So I'll close this issue.
