### ISSUE TITLE
extract wallabag api to a npm component

### ISSUE THREAD

**Issue by Grummfy** [wallabag/wallabagger#33]
Hello,
you should extract the wallabag js client to a npm component to be able to use with some other tools (I'm working on a hubot integration) it could help other to integrate wallabag ;)

**Comment by Rurik19** [comment]
Hello! 
It is a very interesting idea!  Though I cannot promise soon realisation. In 2017 definitely.

**Comment by Rurik19** [comment]
see wallabag-api package

**Comment by Grummfy** [comment]
thanks where can I ind the code of it?
=> so we can improve our own package https://www.npmjs.com/package/hubot-wallabag

**Comment by Rurik19** [comment]
https://github.com/Rurik19/wallabag-api
if you want me to implement more functions - make an issue!

**Comment by Rurik19** [comment]
look also at wallabag-cli package :-)

**Comment by tcitworld** [comment]
cc @Zlitus

**Comment by Grummfy** [comment]
thanks
