### ISSUE TITLE
New articles are archived by default, even though the setting is turned off

### ISSUE THREAD

**Issue by fdw** [wallabag/wallabagger#332]
I tried to save an article to my locally hosted Wallabag instance using this addon in Firefox, but it did not turn up in the "Unread Entries" list. Finally, I checked the archive and found several articles I had saved but never seen as unread.
Checking the addons preferences, "Archive by default when saving the page" is turned off and I don't think I've ever turned it on.

**Comment by majso** [comment]
I had the same issue, and then I realized that I was also clicking the check mark icon, which was archiving the article

![image](https://user-images.githubusercontent.com/55016761/219110798-ba7ac34b-8486-4b5d-aa6a-67ecb42a84b1.png)

**Comment by fdw** [comment]
Thanks @majso, I just tried it. Unfortunately, I did not click on the check mark (it stayed gray), but the article was still archived :/

**Comment by Simounet** [comment]
Can you try it with a fresh Firefox profile please?

**Comment by fdw** [comment]
With a different Firefox profile, it seems to work. I've since reset the buggy one completely, but it still doesn't behave (i.e. new articles are still directly archived).

**Comment by Simounet** [comment]
What addon was it? Could be useful for other people around. Glad to see it working for you!
Closing the issue anyway.

**Comment by stark1tty** [comment]
I am also having this problem.

**Comment by Simounet** [comment]
@stark1tty Is it possible for you to try it with a fresh profile? Try to disable your other extensions?

**Comment by stark1tty** [comment]
I reinstalled and it sorted itself.
