### ISSUE TITLE
After Update (1.16.0) does not work anymore

### ISSUE THREAD

**Issue by walhallaRV** [wallabag/wallabagger#353]
Hi,worked well until the latest Update (1.16.0). Can do what ever I want, it does not save anymore. In the bottom line of the box is shown "Connecting to Wallabag ..." but nothing works.

The web on server is working and I can save manually. But via add-on does not work anymore.

**Comment by virtadpt** [comment]
Same.  I thought I messed something up in my Wallabag install, but then realized that I hadn't changed anything recently.

**Comment by Simounet** [comment]
I'm really sorry to hear that. Can you tell me what browser do you use? Can you try it with a fresh profile?

**Comment by Simounet** [comment]
I'm closing this issue. Feel free to reopen it if needed.
