### ISSUE TITLE
Link to the howto is not valid any more

### ISSUE THREAD

**Issue by HolgerAusB** [wallabag/wallabagger#358]
There is a link to https://wallabag.org/en/news/wallabagger-howto
which content has been (re)moved at some time.

So this link on README.md and on https://addons.mozilla.org/de/firefox/addon/wallabagger/
should be fixed. Maybe in the plugin stores of the other browsers too.

It would be really nice if you could explain the 'Content fetching from the browser' more prominent, because this could be very helpful to save paid content

**Comment by nicosomb** [comment]
The correct URL is https://wallabag.org/news/wallabagger-howto/ 

But we have some work to do on our documentation (this one and more generally, on wallabag ecosystem)

**Comment by Simounet** [comment]
Thank you @HolgerAusB I updated the link on the Firefox addons page and the one on the README file is ok.
