### ISSUE TITLE
Unable to fetch auth token after upgrade to Wallabag 2.6.3

### ISSUE THREAD

**Issue by 4oo4** [wallabag/wallabagger#363]
I can no longer fetch an API token with Wallabager after upgrading Wallabag to 2.6.3, for some reason it only seems to affect this extension and not the Wallabag app or other API integrations I've configured.

In my web server logs I see this when trying to fetch a token:
"POST /oauth/v2/token HTTP/1.0" 400 99 "

**Comment by nicosomb** [comment]
It's a bug in wallabag core. I close this issue. 
Thank you for reporting it.
