### ISSUE TITLE
When I add an emoji as a tag, it appears in double

### ISSUE THREAD

**Issue by NerosTie** [wallabag/wallabagger#37]
When I add an emoji as a tag, it appears in double in the tag area of wallabagger, but everything is ok with Wallabag itself (the emoji is not in double) .

**Comment by Rurik19** [comment]
Hi ! Which emoji do you try to add? Do it consist the ";"  symbol ?

**Comment by NerosTie** [comment]
> Which emoji do you try to add?

A lot. It's the same issue with every emoji.

> ￼Do it consist the ";" symbol ?

I don't understand.

**Comment by Rurik19** [comment]
just give an example, please

**Comment by NerosTie** [comment]
![spectacle lwl468](https://cloud.githubusercontent.com/assets/4572452/22149579/dda2231c-df14-11e6-8f37-510c4733a7dd.png)

Just copy and paste an emoji in the tag area then press space.

**Comment by Simounet** [comment]
@Rurik19 An emoji is not a smiley. It is a special unicode character: https://en.wikipedia.org/wiki/Emoji .
I will try to test that tomorrow.

**Comment by NerosTie** [comment]
@Simounet it was ok in a previous version of wallabagger (when it was very slow to add a tag)

**Comment by Simounet** [comment]
That's confirming my thoughts. Thanks.

**Comment by Rurik19** [comment]
I think that it is fixed by #32, it just not yet released to stores.
![image](https://cloud.githubusercontent.com/assets/1955806/22171591/203f41b6-dfb3-11e6-9c58-ec1cf293a0a2.png)

**Comment by Simounet** [comment]
I just tested it and you're right. I had the issue before #32 and it is fixed on master.
@NerosTie you just have to wait for the next release.

**Comment by NerosTie** [comment]
Thanks!
