### ISSUE TITLE
document the firefox app store link

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabagger#38]
there should be a link to the [AMO](https://addons.mozilla.org/en-US/firefox/addon/wallabagger/) since this now works in firefox (congrats on that, btw, and thanks!). please do mention from which version it works...

**Comment by nicosomb** [comment]
Where do you want to publish this link? On the README here?

**Comment by anarcat** [comment]
yes, sorry that wasn't clear - but the README at least should be updated. but it should also be updated in wallabag itself, in the "Howto" section, which currently links to https://addons.mozilla.org/en-US/firefox/addon/wallabag-v2/

**Comment by Rurik19** [comment]
README changed.

**Comment by Simounet** [comment]
wallabag is pointing to this extension since wallabag/wallabag@6f01c10c88e457ada07ba4a922a93454d58c7e35 and the old extension marked as deprecated (not working into Firefox anymore since Quantum). I think we can close this issue. @anarcat , you can reopen it if you think about something to update.
