### ISSUE TITLE
Suggestion: Support for auth_basic

### ISSUE THREAD

**Issue by koenmetsu** [wallabag/wallabagger#39]
Hi, could you add support for sites behind basic authentication?

**Comment by Rurik19** [comment]
Wallabag itself support only Authorization:Bearer.
Authorization:Basic won't work

**Comment by Rurik19** [comment]
May be I don't understand you right? You want to save pages **from site who requires a basic auth**? In that case - upgrade your wallabag installation to v2.2 - it allows to save auths individually for sites.

**Comment by Simounet** [comment]
I think that he wants to be able to access wallabag through a basic HTTP authentification, like the Android app do. Am I right @koenmetsu?

**Comment by koenmetsu** [comment]
Commuting right now, but yes you're right. I'll try to give more info
later.

**Comment by Simounet** [comment]
The basic use case is that you put your wallabag instance behind a .htaccess?

**Comment by Rurik19** [comment]
or behind Nginx or whatever intermediate server which adds its own auth....

**Comment by Simounet** [comment]
You get the point. 😄

**Comment by koenmetsu** [comment]
Exactly.

**Comment by Simounet** [comment]
Hi @koenmetsu I think we can close this issue with the Fetch content from browser shipped with https://github.com/wallabag/wallabagger/releases/tag/v1.14.0
