### ISSUE TITLE
Redirect loop on authentication when retrieving token (SOLVED)

### ISSUE THREAD

**Issue by cfe84** [wallabag/wallabagger#392]
Writing this in case anyone else ever has the issue. I'm self-hosting wallabag on a shared host.

I had the issue for a few months, where Wallabag would fail retrieving a token. The first call to validate URL was working, and wallabag itself was also working correctly. When debugging the extension with Developer Tools, the network stack would show a redirect loop with a 307 HTTP response from the backend on the oauth/v2/token endpoint... to itself! After spending much time verifying the config on my reverse proxy, I ended up trying to just send the same POST request using CURL, and it worked. After playing with each of the headers, I realized the User-Agent was the culprit.

Something in the stack was triggering that temporary redirect if the user agent was set to the default browser agent (Firefox). So I just override the user-agent, and now Wallabagger works fine. I haven't had a change to figure where in the stack that was failing yet, but at least that's a work-around.

**Comment by Simounet** [comment]
Thanks a lot for your feedback. Really appreciated. 👍

**Comment by cfe84** [comment]
FYI, this was caused by some cPanel firewall on my shared host. I deactivated it and now it works. No clue why I only got that problem with Wallabagger, but maybe that can help someone.
