### ISSUE TITLE
Status of wallabagger for Microsoft Edge?

### ISSUE THREAD

**Issue by HolgerAusB** [wallabag/wallabagger#393]
My standard browser is Firefox. But I had a problem with a website, that doesn't show up properly here, so I loaded that page with MS Edge. And now I wanted to push the browser retrieved content to my wallabag.

But the [wallabagger plugin on edges Addon-pages](https://microsoftedge.microsoft.com/addons/detail/wallabagger/hjgblcdijhgejbicdonbnnadfmpcmgfh) is a 4 year old v 1.10.4 which doesn't support the browser retrieved content option.

The links inside the readme on github, to plugin-pages for Edge and Opera aren't working.
Personally I am not really needing the edge plugin for just this one page.

But as you might know, I try to help other users, when they have problems to catch articles into wallabag. And in some cases, I need to offer them to use wallabagger instead, while I had believed, that it is available for all major browsers - until now.

Has it just been forgotten?

How can I install a current version for Edge?

Alternatively:
@j0k3r, @Simounet: Maybe it is possible to provide wallabag with a pre-defined bookmarklet. The current one, pushes only the URL to wallabag. Maybe it is possible in some ways to do this with the content.

PushToKindle from FiveFilters has bookmarklets for desktop, iOS and Android, which is able to do so:
https://www.pushtokindle.com/bookmarklet#desktop

**Comment by Simounet** [comment]
To me, there is no real plan for wallabagger on Edge. There is already a bit of work to do for Chromium-like browser to update this extension to manifest v3. We will see after that where we can update. You might be able to install the Chrome version but never did that.

About the bookmarklet, you should be able to do that, but it's out of this topic.

**Comment by HolgerAusB** [comment]
Thank you. I wrote a new feature request for the bookmarklet in the wallabag issue section

**Comment by clach04** [comment]
@HolgerAusB are you aware of https://support.microsoft.com/en-us/microsoft-edge/add-turn-off-or-remove-extensions-in-microsoft-edge-9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026 ? I've not had chance to try this yet, BUT I have had success simply installing Chrome extensions from source checkouts in Edge.

RE bookmarklet. My 2 cents, yes this is feasible but a PWA option might be a better option if making a request for a new feature (and would work for almost any browser, desktop and mobile)

**Comment by HolgerAusB** [comment]
Wow, awesome @clach04. I am not using Edge for browsing. I was just asking for people that are using Edge. So I will close my general issue now.

As I am not a developer, I am not sure, how a fetch should work in a PWA (progressive web app?). For my understanding, a PWA is just a website, that don't need browser's menu, buttons and so on, because all navigation is built-in and keeps user on same domain (open new main browser window, if external link). If there would be a wallabag-PWA, how this would help for websites, which needs to be rendered by the browser? So the external page is loaded but wallabag-page wouldn't be there any longer to grab.

**Comment by clach04** [comment]
@HolgerAusB take a like at https://developer.mozilla.org/en-US/docs/Web/Manifest/share_target - my original comment should have suggested "PWA share target" for submitting URLs (although a full PWA could be implemented, I'm not sure if it's worth the effort).
