### ISSUE TITLE
Be compatible with Brave

### ISSUE THREAD

**Issue by HLFH** [wallabag/wallabagger#4]
Hi @Rurik19,

It seems that if `wallabagger` is configured following the [documentation](https://github.com/brave/browser-laptop/wiki/Developer-Notes-on-Installing-or-Updating-Extensions), this extension will be compatible with Brave.

Do you plan to do it?

Related to: https://github.com/brave/browser-laptop/issues/516#issuecomment-253830806

Thanks!

**Comment by Rurik19** [comment]
As I understand Brave is based on Chrome, so I don't see any reasons why wallabager won't work with it.
If I have a little time I try to test it

**Comment by deurk** [comment]
Any possibility to bring this back on the pile?

**Comment by Simounet** [comment]
It's using the Chrome store and I just tested it. It's working. Reopen if necessary.
