### ISSUE TITLE
RequestPolicy addon blocks wallabagger

### ISSUE THREAD

**Issue by azrdev** [wallabag/wallabagger#40]
I'm using Firefox with the [RequestPolicy Continued](https://github.com/requestpolicycontinued/requestpolicy) addon, which blocks access to all 3rd-party domains not explicitly allowed. Different from the [older firefox extension](https://github.com/wallabag/firefox-ext-v2), wallabagger is blocked by RP: when I click on the icon, it instantly displays the error "failed to get app token from <URL> NetworkError when attempting to fetch resource". Disabling RP makes it work as expected.
Can we somehow improve the interaction?

**Comment by tcitworld** [comment]
Did you try creating an exception rule for wallabag in the RequestPolicy settings ?

**Comment by azrdev** [comment]
@tcitworld the RP menu (for the site I want to bookmark) does not contain an entry for this, but you think of manually allowing from `*` to `my wallabag domain` ? That works, although I don't like it, it defeats the purpose of RP IMHO

**Comment by Simounet** [comment]
I'm closing this old issue but feel free to reopen it if it's still a thing for you.
