### ISSUE TITLE
Wallabagger is no longer in the Chrome Web Store

### ISSUE THREAD

**Issue by jabastien** [wallabag/wallabagger#400]
This extension is no longer available because it doesn't follow best practices for Chrome extensions. ChromeOS Version 129.0.6668.62 (Official Build) beta (64-bit) disabled the extension and marked it "This extension was turned off because it is no longer supported"

**Comment by Simounet** [comment]
Hi there, I'm working on a new release to fix that. Will be shipped ASAP. Thanks Google for messing up with webextensions.
