### ISSUE TITLE
No API token 

### ISSUE THREAD

**Issue by lantura** [wallabag/wallabagger#406]
Hi,
I have the problem to get an API token although all fields are marked as green.
Browser is Brave with Chrome extension.
Wallabag is installed on Synology as docker version, log shows no error.
Copy& paste of URL works, but not via browser extension: API token expired.
Any hints?
Thanks

<img width="684" alt="wallabagger" src="https://github.com/user-attachments/assets/0bbb5d11-79f2-4cae-8fd1-9aa1ee852dac">

**Comment by Angiepeck22** [comment]
Hello @lantura 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID WAL07638
Please see the link below to our dedicated support line:
[wallbagger Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by HolgerAusB** [comment]
## ATTENTION, previous post seems to be fishing! Don't click or provide personal information or download files from the link!!!

**Comment by Simounet** [comment]
Hi,
Just to be sure, can you verify the client id and client secret? Some times, there some spaces added after and before when you copy/paste.
After that, can you enable the debug mode at the end of the option page, then try to save a page?Then give me the error result that should appear on the extension page (chrome://extensions/)?

**Comment by lantura** [comment]
Without changing the browser, the URL check no longer works (similar to #408).
How can I activate the debug mode? I can't find anything about this in the online documentation.
Or do you mean the “Save to File” option on the settings page of the Bwrowser extension? 
This generates a JSON File without any error code.
<img width="672" alt="wallabagger2" src="https://github.com/user-attachments/assets/87f433ce-db50-48df-832c-a35e2ac06df9">

**Comment by Simounet** [comment]
I never think about the debug mode hidden after this step. I have to improve this.
In the meantime, you should:
* right click on the page
* click on inspect
* click on the Network table
* fill in your wallabag URL inside the option page input field
* click on the "Check URL" button
* click on the line "info" from the developer window
* click on the response tab on the right side of this window
* give me the content of this box

Sorry about all of these steps.

**Comment by lantura** [comment]
It works without any change only Inspect was activated.
But why is the token only valid for 1 hour?
<img width="661" alt="wallabagger3" src="https://github.com/user-attachments/assets/30958915-3c55-4605-919d-dd5327a2d94b">

**Comment by Simounet** [comment]
That's weird that you have to do nothing except opening the inspector. Don't worry about the token expiration time. It will be renewed by itself.

**Comment by zwiglm** [comment]
hahaha. Totally can second that, that it works with inspector open.
