### ISSUE TITLE
Wishlist: Customizable shortcut for saving

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabagger#41]
Other extensions like Pocket or Instapaper have a configurable shortcut for saving articles.

**Comment by ngosang** [comment]
In the old extension this option was available => https://github.com/wallabag/firefox-ext-v2

**Comment by nicosomb** [comment]
The shortcut is Shift + Alt + w. 
We need to add documentation about that, ping @Simounet @Rurik19

**Comment by ngosang** [comment]
Works for me but should be configurable.

**Comment by Rurik19** [comment]
@ngosang  In chrome-based browsers it is configurable by standard  way - there is a link "shortcuts" in the bottom of chrome://extensions page

**Comment by ngosang** [comment]
I know but I use Firefox and it's not configurable.

**Comment by ngosang** [comment]
Shift + Alt + w is not working in Wikipedia (when logged). It's intercepted and used by the site.

**Comment by gerroon** [comment]
Shift+Alt+w opens the private tab, not sure if this has changed in FF 64

**Comment by Simounet** [comment]
You will be able to change the shortcut from the extension pannel. It's currently available on Firefox Nightly 66. You can look at this ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

**Comment by gerroon** [comment]
Wow, it took them 20 years to let them change shortcuts

**Comment by Simounet** [comment]
You can do it so I'm closing this issue.
