### ISSUE TITLE
API token ?

### ISSUE THREAD

**Issue by Drakone** [wallabag/wallabagger#42]
Bonjour,

j'ai installé wallabag sur mon serveur et wallabagger sur firefox.
Je rentre l'adresse et il me demande des identifiants pour accéder à l'API. Je veux seulement accèder à mes articles...
http://i.imgur.com/MeYMV5O.png

**Comment by nicosomb** [comment]
Bonjour @Drakone ! 

Allez dans la partie "Développeurs" de votre site (prochainement renommée en "Gestion des clients API"). 
Ensuite, laissez-vous guider, vous devriez avoir les infos nécessaires pour tout configurer comme il faut.

**Comment by Drakone** [comment]
Mais je ne veux pas développer... Je veux juste lire mes articles...

**Comment by nicosomb** [comment]
Je sais bien :) 

Cette section n'est pas clairement nommée (c'est pourquoi elle sera renommée). 

Par contre l'extension Firefox ne permet pas de lire : elle permet de sauvegarder des articles. Et elle doit donc communiquer avec wallabag sur votre serveur pour ajouter des articles (d'où cette étape de configuration).

**Comment by Drakone** [comment]
Ah dac 👍 .
Bon bah c'est reglé :).

**Comment by nicosomb** [comment]
Super ! Bonne journée.
