### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by diegombeltran** [wallabag/wallabagger#43]
Firefox 51.0 x64
Wallabag 2.2.1 server
Wallabagger 1.2.0

Clicking on "Get Token" achieves nothing. _Wallabag api token_ remains **not granted**.
If I try to save an article, I get:

> Failed to get app token from http://mydomain.com/oauth/v2/token
> {"error":"invalid_client","error_description":"Client id was not found in the headers or body"}Failed to get app token from http://mydomain.com/oauth/v2/token
> {"error":"invalid_client","error_description":"Client id was not found in the headers or body"}

EDIT: Chromium doesn't work either

**Comment by Rurik19** [comment]
@diegombeltran 
Check URL button works ok? API version appears?

**Comment by Rurik19** [comment]
just recheked on FF 50 and FF 53 - works

**Comment by diegombeltran** [comment]
Check URL works. API version is 2.2.1. How can I debug it?

**Comment by Rurik19** [comment]
press f12 while options page, go to network , press "get token" and look result of POST to 
http://yourlomain.com/oauth/v2/token

**Comment by Rurik19** [comment]
first in parameters tab on the right must be json with 5 fields with your data and in responce tab - json with tokens and expire dates. In case of error there will be json with error details

**Comment by Rurik19** [comment]
params
![image](https://cloud.githubusercontent.com/assets/1955806/22548145/ed8c701e-e966-11e6-85e8-048d78ec0f13.png)
response
![image](https://cloud.githubusercontent.com/assets/1955806/22548192/27576b3c-e967-11e6-9d66-71055a3fd0c1.png)

**Comment by diegombeltran** [comment]
**Some data:**
```
Post: mydomain.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: application/json
Accept-Language: es-ES
Accept-Encoding: gzip, deflate
Content-Type: application/json
Origin: moz-extension://550fb73a-4ab5-4227-85d0-dbd0a5c23c62
Content-Length: 213
DNT: 1
Connection: keep-alive
```
**http://mydomain.com/oauth/v2/token**
```
{"error":"invalid_request","error_description":"Invalid grant_type parameter or parameter missing"}
```

**Aaaand:**
```
500: Internal Server Error
Compile Error: require(): Failed opening required '/MyDirectory/wallabag/var/cache/prod/doctrine/orm/Proxies/__CG__WallabagUserBundleEntityUser.php' (include_path='.:/usr/share/php:/usr/share/pear')
```

Last one looks interesting. I use Nginx and I had to modify web/app.php file and add `libxml_disable_entity_loader(false);` as suggested in official docs. Could it be related to that?

**Comment by Rurik19** [comment]
may be. may be not. Is request body ok? like on first picture - all fields including "grant_type: password" is OK?

**Comment by Rurik19** [comment]
by the way - I use nginx too, and I didn't modify anything in application, just made separate config for it

**Comment by diegombeltran** [comment]
Last version? I had some 500 Internal Server Errors using pdo_mysql and 2.2.1 and I just fixed it adding that line as the Wallabag documentation suggested. There is also a GitHub issue linked to this error.

As for the request:
![captura de pantalla_2017-02-02_12-58-14](https://cloud.githubusercontent.com/assets/7081281/22548638/bbdd0d18-e947-11e6-838c-14f06269eb0b.png)

**Comment by diegombeltran** [comment]
Hello, problem fixed, it was "my fault". I had to restore _web/app.php_ to the original and patch this file: 
`vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php`

Find this line:
`$xmlElement = simplexml_load_file($file);`
Change it to:
`$xmlData = file_get_contents($file); $xmlElement = simplexml_load_string($xmlData);`

Don't forget to clear cache or either way it won't work:
`rm -rf var/cache/*`

[Details here](https://github.com/wallabag/wallabag/issues/2588)

**Comment by Rurik19** [comment]
Yes, it is well known problem, i patch xmldriver after each update. Doctrine project has an issue long time,
