### ISSUE TITLE
Check if article already saved

### ISSUE THREAD

**Issue by janLo** [wallabag/wallabagger#48]
If I save an article, close the dialog and then clock again on the icon to add some tags, it saves the article again. It would be nice if the plugin could check, if the article has already be saved and just has to update the tags.

**Comment by Rurik19** [comment]
Hi! That is in the plans

**Comment by Rurik19** [comment]
It related to #27  and #28 - caching whole article for faster works afterward

**Comment by gnppn** [comment]
I'm adding it would also be nice to have an sign on the plugin icon to see if the page has already been saved (like the pink icon of Pocket).

Thanks!

**Comment by nicosomb** [comment]
@gnppn it's already there: https://github.com/wallabag/wallabagger/pull/36
But not yet deployed on Stores, because it take ages to be updated on stores :/

**Comment by Rurik19** [comment]
@gnppn it deployed to chrome and opera stores,  but for Firefox it needs approvements, which is very long story...

**Comment by Rurik19** [comment]
@gnppn v1.3 just released for Firefox too.

**Comment by Simounet** [comment]
Improved in v1.4 but already shipped in v1.3.
