### ISSUE TITLE
Duplicating tags each time a new tag is added

### ISSUE THREAD

**Issue by KillianKemps** [wallabag/wallabagger#51]
Hello,

I'm using the extension on Firefox 51.0.1, with Wallabag 2.1.5 and I activated "tags with spaces" option.
When I add a new article, each time I add a tag (separated with a `,`), it seems all the tags already entered are duplicated.

So, I have to delete the duplicated tags each time I add a new one.

This issue is not blocking as after some time I have all the tags I want for the article. However, it is very unconvenient to have to delete the duplicated tags each time I add a new tag.

**Comment by Rurik19** [comment]
Hi! Do your tags contais nonascii characters like comma, or emoji? In that case such behaviour is fixed in version 1.3. For Firefox this version is waiting for approvement and will be released soon. As it happens, please update wallabagger and write here if the problem solves or not.

**Comment by KillianKemps** [comment]
I tried again to add tags to an article, actually it happens precisely when I add a tag containing a space. When I do, then the tag containing a space is duplicated.

Maybe you fixed it in Wallabagger 1.3 so maybe should I wait for the update.

**Comment by Rurik19** [comment]
@KillianKemps v1.3 released for Firefox. Update and check the issue, please

**Comment by KillianKemps** [comment]
I updated Wallabagger to v1.3 and it seems I do not have any problem anymore of duplicated tags, even with tags containing spaces.

Great, thank you! 👍
