### ISSUE TITLE
Wrong image ratio in the "saved" popup

### ISSUE THREAD

**Issue by gnppn** [wallabag/wallabagger#52]
Hi!

The popup appearing when an item is saved seems to have a fixed ratio, which doesn't fit many images. It's the case in the linked screenshot. Can it adapt to the actual image file?

Thanks!

![2](https://cloud.githubusercontent.com/assets/22668283/22927491/dc645d34-f2b1-11e6-9bab-d50fb7131240.png)

**Comment by Rurik19** [comment]
v1.4 released!
