### ISSUE TITLE
Shortcut key save wrong tab with multiple windows (Firefox)

### ISSUE THREAD

**Issue by Chocobozzz** [wallabag/wallabagger#59]
If there are multiple Firefox windows, the wrong window is choosen to save the active tab.

I think wallabager should use [the getCurrent method](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/getCurrent) of window API [here](https://github.com/wallabag/wallabagger/blob/master/wallabagger/js/background.js#L113).

**Comment by Simounet** [comment]
Hi,
Thanks for your accurate report. We will look into this ASAP.

**Comment by Rurik19** [comment]
@Simounet I think that we need change "chrome" to "browser" in popup.js

**Comment by Rurik19** [comment]
@Chocobozzz  You are right, I forgot set currentWindow: true in that place in background.js
I fixed it in upcoming v1.4,

**Comment by Chocobozzz** [comment]
Thanks! :)
