### ISSUE TITLE
Blog post about new release of wallabagger

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabagger#6]
Hello @Rurik19! 

Could you write a blog post for wallabag.org about this addon? How to install / configure / use it, etc. with screenshots (or even a video ;-) ). 
You can find blog repository here: https://github.com/wallabag/wallabag.org/tree/master/content/posts

**Comment by Rurik19** [comment]
Tasks:
- [x] installation
- [x] options
- [ ] usage
- [ ] upload images
- [ ] combine blog post

**Comment by Rurik19** [comment]
I created PR https://github.com/wallabag/wallabag.org/pull/37
