### ISSUE TITLE
don't save service browser pages

### ISSUE THREAD

**Issue by Findus23** [wallabag/wallabagger#62]
Just a minor issue, but should be easy to solve:
It would be nice if wallabagger would refuse to save chrome-urls like chrome//newtab/

I assume it's the same issue with about:// URLs in Firefox.

**Comment by Rurik19** [comment]
I even done this :) In upcoming v1.4 I have a function 
`const isServicePage = (url) => /^(chrome|about|browser):(.*)/.test(url);`

**Comment by Findus23** [comment]
Perfect, thanks.

**Comment by Rurik19** [comment]
v1.4 released!
