### ISSUE TITLE
Wallabagger credentials configuration

### ISSUE THREAD

**Issue by ngosang** [wallabag/wallabagger#64]
Why is need to specify the user credentials (user and password) and the api credentials (client id and client secret)??
In wallabag android app you only need to fill user credentials (user and password).

![2017-03-05 16_56_59-administrador de complementos](https://cloud.githubusercontent.com/assets/10577978/23588934/1efb95e6-01c5-11e7-9433-067d5ee60080.png)

**Comment by jlnostr** [comment]
The reason for that is that wallabager is using the new API of wallabag v2. This API requires both client id and client secret.

The android app instead is relying on an older method fetching the content that do NOT require both these values. For the future you can remember that every app that is using the new wallabag v2 API requires both client id and client secret.

@wallabag/core Any plans for supporting OAuth like GitHub does it using a popup where the user just needs to enter his credentials?

**Comment by Rurik19** [comment]
@wallabag/core It will be great to have API call to retrieve information about existing client for the user

**Comment by Rurik19** [comment]
@jlnostr  What is that older method? Does it allow to save and modify articles apart of just fetching?

**Comment by ngosang** [comment]
> This API requires both client id and client secret.

What about having client id and client secret but no user and password?

**Comment by jlnostr** [comment]
@Rurik19 Plain RSS feeds that only allow the fetching of articles, nothing else. Supported since wallabag v1.
@ngosang That's an interesting idea :)

**Comment by Rurik19** [comment]
@ngosang with no user and password is impossible to get application token and without token - API just doesn't work.

**Comment by ngosang** [comment]
> The android app instead is relying on an older method fetching the content that do NOT require both these values. For the future you can remember that every app that is using the new wallabag v2 API requires both client id and client secret.

I'm not completely sure but I think wallabag-app (current master branch) only uses wallabag api v2 https://github.com/wallabag/android-app/pull/370

**Comment by tcitworld** [comment]
Yes, but it uses old methods (connect directly to the app) to generate itself the client if it doesn't already exists. That **bad** and should be dropped before next release.

**At the same time**, the client creation in the server should be really better, and offer an experience with something like facebook, twitter, or github auth.

**Comment by jlnostr** [comment]
@tcitworld In case there's an update of how the automatic client generation is updated, notify me, because my windows app is creating the client automatically like the android app.

**Comment by Rurik19** [comment]
There are many issues on this subject in wallabag/wallabag, like #2583, #2568. #2800. It all api matters, not clients, so I close this one.
