### ISSUE TITLE
Firefox add-on authentication token error

### ISSUE THREAD

**Issue by zoncrd** [wallabag/wallabagger#66]
I filled the options form with my username, password, Client ID and Client secret

![selection_001](https://cloud.githubusercontent.com/assets/6806779/24324493/8b2675d4-1187-11e7-8563-da0b94751201.png)

But I get this error when I try to get the auth token:

```
Failed to get app token from https://v2.wallabag.org/oauth/v2/token
JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**Comment by tcitworld** [comment]
v2.wallabag.org will be shut down soon (when framabag.org will be migrated), so you should look at somewhere else. I doubt that wallabagger is compatible with wallabag 2.1.5.

**Comment by zoncrd** [comment]
Ok, I found out "where to look at". I registered at wallabag.it, so the correct url is https://app.wallabag.it.
Thank you for the prompt response.

**Comment by Rurik19** [comment]
@nicosomb 
> I doubt that wallabagger is compatible with wallabag 2.1.5.
Of course it is compatible. Error 
`JSON.parse: unexpected character at line 1 column 1 of the JSON data`
means that server returns html (or whatever) instead of JSON

**Comment by nicosomb** [comment]
FYI, it's a @tcitworld post ;-)

**Comment by Rurik19** [comment]
@nicosomb sorry :-)

**Comment by tcitworld** [comment]
I said that because there was versions without the `api/version` endpoint.

**Comment by Rurik19** [comment]
@tcitworld Error in this issue is about /token endpoint.
