### ISSUE TITLE
Open saved article when I click on the title

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabagger#67]
When I click on the article title in the popup, I want that wallabagger open a new tab with my saved article (in my wallabag account). 

![capture d ecran 2017-03-31 a 11 56 23](https://cloud.githubusercontent.com/assets/121870/24545850/2e20a158-1609-11e7-9bd4-8fdab61ab6fe.png)

**Comment by Rurik19** [comment]
Could you get more details, please? This thing should work since the very first version...

**Comment by nicosomb** [comment]
I will try again, but I think that when I click on the link (in blue), it does nothing.

**Comment by Simounet** [comment]
It's a bug on Firefox. I'll look into this.
