### ISSUE TITLE
When an article is already saved, no need to "saving the page to wallabag"

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabagger#68]
If I click on the green icon (the addon already knows that the article is saved), we don't need to launch the "save the page to wallabag" process. We just need to display the popup.

**Comment by Rurik19** [comment]
Which version do you mean? v1.4 does exactly as you describe.

**Comment by nicosomb** [comment]
I use the v1.3.

**Comment by Rurik19** [comment]
v1.4 is all about caching and async works. So wait a little or try v1.4beta

**Comment by Rurik19** [comment]
v1.4 released!
