### ISSUE TITLE
URL check fails with self-signed SSL certificate and/or custom port 

### ISSUE THREAD

**Issue by nmaggioni** [wallabag/wallabagger#71]
The same behavior as #70 is presented when an URL with self-signed SSL certificates served on a custom port is given to the Chrome extension's settings.

`https://[DOMAIN].ddns.net:32370`, for example, fails without explanations, even though visiting it via a browser works fine. Wallabag is served via NGINX and a self-signed certificate created with the OpenSSL utilities.

**Comment by Simounet** [comment]
Thanks for this bug report. We will look into this. In the meantime, can I suggest you to look at https://letsencrypt.org/ if you can. It's a free certificates provider, avoiding you these annoying messages.

**Comment by nmaggioni** [comment]
Thanks for the tip, I've used Let's Encrypt for other cases, but this is a small private deployment that needs to be reached from both WAN and its LAN. I'll look into multi-domains certificates, anyway!
