### ISSUE TITLE
new tag to alltags 

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabagger#72]
After adding brand-new tag in should appear in the alltags array to be used in autocomplete for future articles

**Comment by gerhard-tinned** [comment]
It reads like the problem I have. If so ... +1

When I try to add a tag to to the saved page, it does not accept it. It seems it is only possible to tag a saved page with tags already existing.

(Using Version: 2.1.6 via Docker; Latest version via Docker is broken)
