### ISSUE TITLE
Integrate the icon to Firefox's Reading Mode

### ISSUE THREAD

**Issue by aleksandar-todorovic** [wallabag/wallabagger#74]
Feature request:

My workflow is heavily-dependent on Firefox's Reading Mode. Once triggered, the left toolbar looks like this:

![screenshot from 2017-04-16 19-31-12](https://cloud.githubusercontent.com/assets/4890548/25072945/4f54e364-22db-11e7-92c6-0d63ad7eb09f.png)

I would love to see the wallabagger icon added here.

Seems like this is just a webpage, and manipulating the DOM seems like all that is needed. Quick F12 shows me that this is the code behind the Pocket icon:

    <button class="button" style="background-image: url('chrome://pocket/content/panels/img/pocket.svg#pocket-mark')" id="pocket-button" title="Save to Pocket"></button> 

I also remember myself being able to completely hide the sidebar and / or tweak its look using Stylish a couple of Firefox versions back, so this feature request seems rather feasible to me.

**Comment by Rurik19** [comment]
Join this issue to #73
