### ISSUE TITLE
Option to remove the Pocket integration in Firefox's extension settings

### ISSUE THREAD

**Issue by aleksandar-todorovic** [wallabag/wallabagger#75]
Once I had the wallabagger all set up, seeing the Firefox's Pocket integration seemed kind of redundant to me. So, my second feature request is either a small checkbox that will say something like "Disable Pocket integration" and would change the `extensions.pocket.enabled` settings to false.

Alternatively, I think that a small note to Firefox users in the preference window stating something like "Tip: If you want to remove the Pocket integration, disable extensions.pocket.enabled in the about:config window` would also do the trick, if manipulating browser settings isn't that easy to implement.

I've seen password managers asking to disable Firefox's default password manager, so I thought what the heck, wallabag might as well do the same.

**Comment by Rurik19** [comment]
What about Evernote extension? Or OneNote or whatever else ?
I think such behaviour can be treated as bad concurency :-) It should definintely be user decision - to save or to remove other extensions. So - no, we won't do that.
