### ISSUE TITLE
'Get token' in Chrome extension d.oesn't seem to do anything.

### ISSUE THREAD

**Issue by akwala** [wallabag/wallabagger#76]
Wallabag 1.3 extension in Chrome

When configuring, after checking URL, entering Client ID & Secret, and entering Username & Password, clicking 'Get Token' has no apparent effect.

![wallabagger1 3-chr-options-token](https://cloud.githubusercontent.com/assets/1786/25098909/44fceb62-2378-11e7-91c4-09630a7563cf.png)

**Comment by Rurik19** [comment]
"Granted" and green borders shows that token is OK. Do extension works normally?

**Comment by akwala** [comment]
Sorry, I didn't look carefully. This is not an issue.
