### ISSUE TITLE
wallabager extension out of date on Mozilla add-ons site

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabagger#77]
https://addons.mozilla.org/fr/firefox/addon/wallabagger/ says 1.3, here it says 1.4... anything happening we should know? :)

ETA?

Thanks!

**Comment by Simounet** [comment]
We are waiting for a validation on the Add-on for Mozilla store… Sorry about that.

**Comment by azrdev** [comment]
Validation is still ongoing?

Chrome Web Store still seems to have 1.3, too.

**Comment by Simounet** [comment]
Firefox addon is now up-to-date. We're still waiting for the Chrome one.

**Comment by Rurik19** [comment]
Chrome extension is published as well.

**Comment by anarcat** [comment]
well, that's great, but it made the plugin completely unusable now, see #86
