### ISSUE TITLE
Right-Click save fails in FF 53.0 Linux

### ISSUE THREAD

**Issue by gruentee** [wallabag/wallabagger#78]
* When trying to save a page via the context-menu, the toolbar button turns yellow and after a while red.
* Page is not saved.

Screeshot of the settings screen:

![wallabagger_settings_screen](https://cloud.githubusercontent.com/assets/923759/25476497/a83fd8be-2b3a-11e7-8e16-116a0a5516df.png)

**Comment by Simounet** [comment]
Hi,
Can you give us the debugs infos following these steps:
- go to `about:debugging#addons`
- check in `Enable add-on debugging`
- click on wallabag `debug` link
- click on `ok` to accept incoming connections
- add some page through the context-menu
- give us the entries on the console tab of the new window opened

**Comment by gruentee** [comment]
Oh, sorry. I obiously totally forgot about this issue and the information you requested. Works fine for me now, you were right to close it ;-)
