### ISSUE TITLE
Show read and favorite status

### ISSUE THREAD

**Issue by jcharaoui** [wallabag/wallabagger#8]
When I visit a page which was already added and has the read or favorite status, the extension dialog doesn't show it. It always shows read and favorite as "off". If a page was marked as read or favorite, then the extension dialog should show that.

**Comment by Rurik19** [comment]
Just rechecked - all works fine.
- save article , set fav and arc status
- open this page in another browset
- save it again - fav and arc status is set

What is yours : 
- versions of wallabag and wallabagger 
- browser
- url to save?

**Comment by jcharaoui** [comment]
I tested on 2.1.5 and it works. I was using an old version.
