### ISSUE TITLE
Cannot install on Firefox

### ISSUE THREAD

**Issue by corrupt** [wallabag/wallabagger#83]
Been trying to install Wallabagger in Firefox for a while. Installation from the official repository fails with this:
![spectacle s15403](https://cloud.githubusercontent.com/assets/365169/26244424/e059282a-3c8f-11e7-91c8-e13d4e5e2622.png)

The same happens when downloading and trying to install manually.
The Browser console displays warnings about unexpected keys in the manifest, which I suspect are there for Chrome compatibility. 
There is also an error about a missing ID.
![console](https://cloud.githubusercontent.com/assets/365169/26244534/4c853f52-3c90-11e7-9137-949571e63ae4.png)

I tried modifying the manifest to include an ID, but to no avail. Changes made as follows:
```json
"applications": {
	"gecko": {
		"id": "wallabagger@github.com"
	}
},
```

Of course I had to remove the signature afterwards. I'm using the most recent Version of Firefox (53.0.2) but configured it not to require signatures, so technically I should be able to install it. However, if I try, nothing happens at first, and when I revisit the addons page later, it displays this:
![screenshot_20170519_1as24543](https://cloud.githubusercontent.com/assets/365169/26244702/20114276-3c91-11e7-92e0-6d176b793fab.png)

This happens every time I try. Deleting the unsupported keys from the manifest will not change this, even though all warnings and errors then disappear from the browser console.

**Comment by tcitworld** [comment]
Same version, can't reproduce. Maybe you have some weird setting in `about:config` ?

**Comment by corrupt** [comment]
That would explain why nobody else experiences this. But Wallabagger is the only addon I've seen this with. Been through Mozilla's Addon Troubleshooting acticle already and nothing changed. I'll look into that a bit more.

**Comment by tcitworld** [comment]
> I'm using the most recent Version of Firefox (53.0.2) but configured it not to require signatures, so technically I should be able to install it.

Did you try installing installing from the Mozilla Addons website without that setting ?

**Comment by corrupt** [comment]
Yes. Configured that fairly recently.
I'll create an empty profile later and try again. Will report back.

**Comment by corrupt** [comment]
You're right. Apparently this is a side-effect of disabling addon signing. It would still be interesting to know why this only happens with Wallabagger. I do have other WebExtensions installed so it's not that. If you decide to look into this, I'll be happy to test. Maybe adding an ID to the manifest is a first step. Thanks for looking at this.
