### ISSUE TITLE
wallabager still check to see if the page is saved

### ISSUE THREAD

**Issue by rezad1393** [wallabag/wallabagger#84]
I have disabled the option in the addon that check for existence of the page in saved wallabag pages. but it gets reenabled and it still checks for any page I visit in firefox .

**Comment by Simounet** [comment]
Did you restart Firefox? Can you give us the debugs infos following these steps:

- go to about:debugging#addons
- check in Enable add-on debugging
- click on wallabag debug link
- click on ok to accept incoming connections
- add some page through the context-menu
- give us the entries on the console tab of the new window opened

**Comment by rezad1393** [comment]
I exported the addon setting and saw that it had this at the end:
"AllowSpaceInTags":false,"AllowExistCheck":null,"Debug":false

I changed the null to false and imported it and it fixed the issue.

**Comment by Simounet** [comment]
What is your Firefox's version? Do you have any error in the console?

**Comment by rezad1393** [comment]
I didn't heck the errors then.
I just found that wallabager was doing this by seeing it in umatrix addon log that it was making connections to my wallabag with url of the websites.
maybe it was a one time thing because after importing the exported and fixed preferences it works ok now.

my firefox i 53 and is on linux x64.

if this has not happened to anybody else please close the issue.

**Comment by Simounet** [comment]
But now, when you toggle the check to see settings, is it saved correctly?

**Comment by rezad1393** [comment]
yes.

**Comment by Simounet** [comment]
Ok so I'm closing this issue and we will see. Thanks for your feedback.

**Comment by rezad1393** [comment]
this is a very weird issue.
when I restarted firefox it seems to be gone.

so I am not really sure what happens.

maybe after changing the setting, firefox needs to be restarted?

**Comment by Simounet** [comment]
Yes. Firefox needs to be restarted.

**Comment by rezad1393** [comment]
ok.
thanks.
if that is the case then I think this is not a issue for me anymore.

but to be exact at first my issue (as mentioned in first post) was that the option would get reenabled when I disabled it and then closed and opened addon page in firefox.
but you are free to close this if you want.
