### ISSUE TITLE
url doesn't connect (firefox 53.0.3 32 bits windows 7)

### ISSUE THREAD

**Issue by ours1** [wallabag/wallabagger#85]
when I fill the **wallabg url** with "framabag.org" the button **check url** doesn't return anything. The firefox's console says :
L’utilisation de « document.createAttribute() » est obsolète. Utiliser « element.setAttribute() » à la place.
L’utilisation de « setAttributeNode() » est obsolète. Utiliser « setAttribute() » à la place.

**Comment by Jenselme** [comment]
I have the same problem. Tested on Firefox 53.0.3 and on Firefox nightly with my wallabag server (wallabag.jujens.eu). According to the server logs, no request is made to the server. My console is empty.

**Comment by ours1** [comment]
By disabling all the addons, wallabagger did connect ; and it works fine now, even after enabling back every addons -except Pocket I've erased.

**Comment by Jenselme** [comment]
@ours1 just did that and it worked. Thanks for the tip.

**Comment by Simounet** [comment]
I would like to fix that but I can't reproduce it. Can you try to install wallabagger into a fresh Firefox profile please?

**Comment by ours1** [comment]
Yes with pleasure but... with a fresh firefox it will work (if fresh Firefox means with no addons) because precisely this is what I've done to make it work, I installed wallabagger with no addons enable.

**Comment by Simounet** [comment]
Could it be the Pocket extension or do you have any hint about the extension that made the problem appearing?

**Comment by ours1** [comment]
No hint, I'll try few install and uninstall of addons -and Pocket first, (maybe adblockers too are supposed to be more guilty)

**Comment by ours1** [comment]
Actually as it is very easy to display image here, I show you the list of my addons ; in case there is a couple of them that strikes you I'll test these ones first

![2017-06-01 12_19_29-url doesn t connect firefox 53 0 3 32 bits windows 7 issue 85 wallabag_wa](https://cloud.githubusercontent.com/assets/29060382/26675671/20da2c7a-46c5-11e7-9168-b072a94568b3.png)

**Comment by ours1** [comment]
OmniSidebar   http://fasezero.com/    is preventing from the _wallabag url_ field to work

@Jenselme are you using this addon ?

**Comment by Jenselme** [comment]
I don't have this extension. The problem seems to be with the [uMatrix](https://github.com/gorhill/uMatrix) extension.

**Comment by Simounet** [comment]
I'll investigate this issue but you can look at the @anarcat solution proposed here: https://github.com/wallabag/wallabagger/issues/86#issuecomment-306495998

**Comment by weverett** [comment]
I've just had the same problem with wallabagger 1.4.1 and firefox 55.0.3. I disabled all my extensions and the check URL worked. I set up Wallabager and enabled my extensions and everything still works. The closest thing I have to a common extension with @ours1 is uBlock Origin which shares a similar code base with uBlock (and is probably similar to uMatrix).

**Comment by VagabondAzulien** [comment]
Adding my two-cents: I've narrowed down this issue to uMatrix on my machine. I added the following rule to the "My Rules" tab in the uMatrix dashboard" `* app.wallabag.it xhr allow`. Obviously allowing XHR on any site for `app.wallabag.it` is a bit risky, but it seems to solve the issue.

**Comment by Simounet** [comment]
I'm closing this old issue but feel free to reopen it if it's still a thing for you.
