### ISSUE TITLE
TypeError: can't convert null to object

### ISSUE THREAD

**Issue by anarcat** [wallabag/wallabagger#86]
There was some update of my wallabag plugin in Firefox recently and it can't connect to the server anymore. All the settings are gone, when I go in the configuration. When I try to enter the URL again and click "check URL", nothing happens. In the Javasacript console, I see this:

```
09:19:45.500 TypeError: can't convert null to object 1 options.js:255:13
	assign self-hosted
	OptionsController.prototype.checkUrlClick moz-extension://23f3052b-96fa-4cc2-b891-724604274ddc/js/options.js:255:13
	bound  self-hosted
```

The plugin says "last updated 2017-05-31" and version 1.4.1. This is under Firefox 50.1.0: `Build identifier: Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0` running under Debian Stretch.

**Comment by azrdev** [comment]
@anarcat for a quick fix, you should be able to downgrade from AMO as it shows previous versions on the bottom of the addon page (<https://addons.mozilla.org/firefox/addon/wallabagger/versions/>).

For fixing the issue, have you looked into the debug console (Ctrl+Shift+j) ? Maybe try watching it while re-entering your credentials into the wallabagger config

**Comment by anarcat** [comment]
> For fixing the issue, have you looked into the debug console (Ctrl+Shift+j) ? Maybe try watching it while re-entering your credentials into the wallabagger config

Well yes i did, the error message that shows up there is all that I see, and it's the title of this bug report. :p

**Comment by Rurik19** [comment]
I've just installed FF 50.1.0 and get this error. So I can advice you two solution:
- upgrade to FF 53 - it works there
- setup wallabagger in chromium, save setup to file, then load setup to FF

code in options.js will be changed in future version, but with mozilla store updates gets monthes...

**Comment by anarcat** [comment]
> * upgrade to FF 53 - it works there

... i don't have that opportunity right now. i'm running Debian stretch. it has Firefox 50, released a few months ago. you're asking me to run a release of Firefox that was published about 6 weeks ago. i think that would be an unfair requirement. :p

> * setup wallabagger in chromium, save setup to file, then load setup to FF

so i tried that, and it didn't work: i can save the creds from chrome and load them into firefox, and they show up then. but the "Check URL" or "get token" buttons do nothing (nothing in the console, no change in the status), and when i quite the addons preferences dialog, the settings get wiped.

**Comment by Rurik19** [comment]
if the creds are valid in chrome, after load them to FF you are able not to check url, just get token.

**Comment by anarcat** [comment]
i tried exactly that, nothing happens.

**Comment by anarcat** [comment]
I can confirm that downgrading to the 1.3 release fixes this issue. I am not in a position to upgrade to Firefox 53 unfortunately and I hope this can be fixed soon!

**Comment by anarcat** [comment]
Actually, the 1.3 release "works" in that the settings page works, but I still can't save bookmarks. I get this error when I click on the W button:

> Failed to save page https://example.net/wallabag/api/entries.json
> NetworkError when attempting to fetch resource.

example.net is running fine..

**Comment by Rurik19** [comment]
Hi. That "expired" on the options page is unsignificant bug, tokens refreshes authomaticaly. 
But that network error is bad - can you see server response on network tab in debug window?

**Comment by anarcat** [comment]
Not really: i do not see a network request in Firefox's "Network" tab - I'm not sure what's going on there. I also do not see anything in the console immediately, but after fiddling around, I do see this:

```
TypeError: NetworkError when attempting to fetch resource.
```

**Comment by anarcat** [comment]
Any other ideas? :)

**Comment by Simounet** [comment]
Can you try it on a fresh profile?

**Comment by anarcat** [comment]
@Simounet a fresh profile, under firefox 50.1 and wallabager 1.4.1, yields those results:

1. entering the URL of the Wallabag site and clicking "Check URL" does nothing
2. loading the working configuration from the chromium configuration backup works, and the "Check URL" button then works, but not the "Get token" button, which does nothing
3. the Wallabag button *looks* like it works (it pops up the usual dialog with the page title) but doesn't save the page (it says "Loading wallabag API...", gets stuck there and the page isn't saved)

I *am*, however, able to make Wallabager 1.3 in a fresh Firefox 50.1 profile. I was able to pinpoint uMatrix as being the other extension conflicting with Wallabag, which is strange because I didn't have such issues before.

So the workaround, for now for me, is to:

1. disable uMatrix
2. downgrade to Wallabager 1.3

**Comment by Simounet** [comment]
This is not the first time that uMatrix makes wallabagger to fail. I'll investigate that later.
About your Firefox version, it is not so handy for us to manage API capabilities on an evergreen browser like Firefox but we'll try to make it better.

**Comment by anarcat** [comment]
I wouldn't worry too much about uMatrix: we are power users and can figure out that stuff on our own, because blocking things like XHR and Javascript will yield weird results here and there. It would be nice if Wallabag would show up as a "behind the scenes" element, which I think was the case before, but that's no big deal...

But I think it would be a priority to make Wallabager 1.4+ work with ESR releases. I was mistakenly thinking I was running some newer ESR, but Firefox 50 is now unsupported, so that was my fault. :( It looks like I installed the Firefox release from Debian unstable a while back, and didn't set proper hooks to make sure it followed the unstable branch.

So after an upgrade, I can confirm that Wallabager 1.4.1 *does* work with Firefox ESR 52.0. So I'll just close this issue and apologize for the noise here... Hopefully the uMatrix stuff will be useful for others, e.g. in #85 at least. :)

**Comment by Simounet** [comment]
Don't worry, it kept us on track to think about ESR users. ;)

**Comment by anarcat** [comment]
it looks like the origin of requests is more random than i thought - even with Firefox 52 and Wallabager 1.4.1, i still get trouble when applying the above recipe with uMatrix. Basically, i need to whitelist an arbitrary list of sites in order for the requests to go through.

So I ended up adding the following rule:

```
* example.net * allow
* example.net cookie allow
* example.net frame allow
```

where `example.net` is the domain of my wallabag instance. this way that site can execute javascript, deal with cookies and frames on *any* other site. this is a security hole in some way, but at least it works.
