### ISSUE TITLE
Firefox add-on corrupt

### ISSUE THREAD

**Issue by Rian83** [wallabag/wallabagger#88]
Hello,

I try from this url to install the firefox add-on : https://addons.mozilla.org/fr/firefox/addon/wallabagger/
But I get an error, the add-on appear to be corrupted.

I tried to apply this https://support.mozilla.org/en-US/kb/unable-install-add-ons-extensions-or-themes#w_corrupt-extension-files but it doesn't change anything.

Is it normal ? 

![2017-06-06 17_11_52-wallabagger __ modules pour firefox](https://user-images.githubusercontent.com/1486562/26836527-665eb936-4adb-11e7-8ee2-cac2b8c464e8.png)

Nom 	Firefox
Version 	48.0.2
Identifiant de compilation 	20160823121617

**Comment by Simounet** [comment]
Hello there,
Can I know why you are still using an outdated Firefox version? The last wallabagger version needs at least Firefox 52.

**Comment by Rian83** [comment]
Hi,

I don't know why, my firefox tell me that it's up to date ...
But on firefox info, it's written that it's compatible with "Firefox 48.0 et supérieures"

**Comment by Rian83** [comment]
Hi,

I don't know why, my firefox tell me that it's up to date ...
But on firefox info, it's written that it's compatible with "Firefox 48.0 et supérieures"

**Comment by Simounet** [comment]
Which is your operating system? Can you try to update Firefox?

**Comment by Rian83** [comment]
Win7.
Ok so my firefox was buggy ... I force the update (I downloaded the installer and try to install it, and it updated my version). Now I'm in the 53.0.3. And the add-on installation worked.

But weird thing why firefox web page tell me that it's compatible to 48.0 and it's not ..

**Comment by Simounet** [comment]
Because we didn't filled-in the minimal Firefox version required. I'll fix that in the next release.

**Comment by Rian83** [comment]
Ok that's why !
