### ISSUE TITLE
1.4.1 Firefox: Unable to tag multiple added links

### ISSUE THREAD

**Issue by pVesian** [wallabag/wallabagger#89]
Hi,

I'm using 1.4.1 on Firefox 53.0 on Debian. I can't add multiple items and tag them.

To reproduce:

- go on a youtube channel
- add a video, tag it
- add a second video, you can't tag it, the first one is still there

Thanks!

**Comment by Rurik19** [comment]
I not understand: the page on youtube stays the same? If it is - you can save only the page, not separate video from there

**Comment by pVesian** [comment]
I'm not sure I understand your comment. I want to be able to add more than one link with right click -> Wallabag it.

**Comment by Rurik19** [comment]
1) You right click on several video and wallabagit them
2) then you want to tag its 
Right?

**Comment by pVesian** [comment]
1. I right click a video, wallabag it and tag it
2. I want to repeat the process on other videos/links and this is where it bugs

**Comment by Rurik19** [comment]
This is the difference: 
1) When you right click a video you save to wallabag THAT page, with the URL of the video
2) When you click on the wallabag icon, you save THIS page from browser tab, in your case - the page of the channel, and you set tags on the saved pade of the channel. To tag pages, saved by rightclick on links, you should go to wallabag.

**Comment by pVesian** [comment]
OK. Could my idea be implemented? If not, could the labels change to be
more clear about this?

Le 21 juin 2017 12:36 PM, "Yuriy Evdokimov" <notifications@github.com> a
écrit :

**Comment by Rurik19** [comment]
there is an issue #47 about this problem. May be there will be notification about saved page with tag controls.
