### ISSUE TITLE
Add hint to icon when page was already added

### ISSUE THREAD

**Issue by jcharaoui** [wallabag/wallabagger#9]
It would be quite useful for the extension icon to show a little hint whenever the current page was already added to Wallabag.

Instead of sending a query to the Wallabag server on each URL load, it can maintain an internal cache of URLs, like the old [Bookie extension](https://github.com/bookieio/bookie-chrome) did.

**Comment by Rurik19** [comment]
There is an "exists" api now in wallabag, it may be used. Thanks for the good idea

**Comment by Rurik19** [comment]
fixed in v1.1
