### ISSUE TITLE
Stopped working with Firefox Developer Edition

### ISSUE THREAD

**Issue by rmenessec** [wallabag/wallabagger#90]
I'm unable to use Wallabagger with the latest Developer Edition, which is based on 55.0b1. Clicking the icon to save pages opens the usual dialog window, but Wallabagger claims to be saving the page forever.

Opening the options dialog shows that either all the configuration values were lost, or they're not being displayed / retrieved. Attempting to configure the extension again and run the server test (I'm using Framabag) does nothing.

From the developer console:
```
10:13:27.090 The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.  options.html
10:13:27.093 ReferenceError: browser is not defined[Learn More]  options.js:344:9
	init moz-extension://318df40c-d3f1-4f68-965a-487936372a70/js/options.js:344:9
	<anonymous> moz-extension://318df40c-d3f1-4f68-965a-487936372a70/js/options.js:356:5
```

**Comment by tcitworld** [comment]
Works properly with Firefox Nightly (56), though the credentaials were also lost. Also with Framabag.

**Comment by rmenessec** [comment]
Just updated to the 55b2 Developer Edition. No change; "Check URL" still does nothing.

**Comment by Rurik19** [comment]
Just checked with FF DE v55b3 - works ok. Do you have other extension installed? Please check on clear installation, without other extensions.

**Comment by rmenessec** [comment]
@Rurik19 That's a major time commitment that you're asking for. I'm sorry, but I can't do it.

Also, updating to DE 55.0b3 has not changed anything for me.

**Comment by tcitworld** [comment]
Just check without extensions like NoScript, adblockers, privacy extensions and so on, or whitelist Framabag in them.

**Comment by rmenessec** [comment]
@Rurik19 Appears to be caused by or related to https://bugzilla.mozilla.org/show_bug.cgi?id=1316441

I can confirm that this bug also damages the functionality of https://addons.mozilla.org/en-US/firefox/addon/archiver-menu/ (another WebExtension) and prevents options from being set.

Also affects Mozilla's Test Pilot addon and their Containers Experiment addon. IoW: all WebExtensions that I have installed.

This almost certainly can't be caused by a single extension. It's much more likely that it's one of the 200-300 Firefox options I've changed from the defaults, which I can't possibly track down on my own.

I strongly suggest you get in contact with the Mozilla devs.

**Comment by Rurik19** [comment]
@rmenessec I will test it on FF on linux as soon as I get it. On Windows this bug don't appears at all

**Comment by rmenessec** [comment]
@Rurik19 Windows here, too. Like I said:

> This almost certainly can't be caused by a single extension. It's much more likely that it's one of the 200-300 Firefox options I've changed from the defaults, which I can't possibly track down on my own.

**Comment by rmenessec** [comment]
Result!

I've narrowed down the problem a bit further, using Developer Edition 55.0b5: Wallabagger works correctly if the options are entered in about:addons. However, if I open the options in a window (frex: using [Extension Options Menu](https://addons.mozilla.org/en-US/firefox/addon/extension-options-menu/)), the entire options window is empty (defaults) and completely non-functional.

The exact same sort of problems still apply to official Mozilla extensions using windows / frames like [the Containers experiment](https://testpilot.firefox.com/experiments/containers).

Now that I have an exact procedure nailed down, this should be easier to duplicate. I won't even try to guess why having the extension options open outside core browser chrome is a problem.

This looks more like a Mozilla problem rather than a Wallabagger problem. However, the result is the same: Mozilla takes extension developers more seriously than end users. **Please** contact the Mozilla developers and let them know that this is going on.

**Comment by nicosomb** [comment]
Can we close this issue?

**Comment by rmenessec** [comment]
I certainly can't help triage it; I'm stuck on Firefox 56.0b12 so I can keep XUL extension support until NoScript is properly ported to WX. 😛

I can add that some problems I've had with this and other WX extensions have been fixed in part by updated releases of "hybrid" NoScript and I think in part by changes between Firefox 54 and 56, so I suspect at least part of the problem is either NoScript flaws or bad WX browser implementation by Mozilla. Maybe both. 😛

**Comment by Simounet** [comment]
I'm closing this old issue but feel free to reopen it if it's still a thing for you.
