### ISSUE TITLE
Some characters are not decoded properly

### ISSUE THREAD

**Issue by guiweber** [wallabag/wallabagger#95]
For example, the apostrophe from this site's title appears encoded in wallabagger:

![untitled](https://user-images.githubusercontent.com/7825368/28628318-59603b72-71f2-11e7-8acd-c77aaa2c1c4d.png)

Wallabagger version: 1.4.1
Browser: FF 54.0.1

**Comment by Rurik19** [comment]
Hi! How this title looks in wallabag interface?

**Comment by Rurik19** [comment]
just checked in FF54
![image](https://user-images.githubusercontent.com/1955806/28659706-d65ea410-72c9-11e7-9ae6-458da9ce7e92.png)

**Comment by Rurik19** [comment]
I understand - that title after editing

**Comment by guiweber** [comment]
Ah yes sorry I forgot I had edited the title!

Thanks for the fix : )

**Comment by Simounet** [comment]
And it should be fixed by the last version (v1.4.3) if you saw the wallabagger last update.
