### ISSUE TITLE
Unable to add tags through wallabagger

### ISSUE THREAD

**Issue by guiweber** [wallabag/wallabagger#96]
I am able to add and remove pages from wallabagger just fine. If I add tags directly from the wallabag web interface, I see them in wallabagger and can remove them from there. However, I am not able to add new tags through wallabagger.

Wallabag version: 2.2.3
Wallabagger version: 1.4.1
Browser: FF 54.0.1

**Comment by Rurik19** [comment]
Hi! how do you add it? it should be added when you press space or enter after typing tag

**Comment by guiweber** [comment]
Ah, I think I found the issue. It looks like in 1.4.1 "enter" doesn't work. You have to press "space" to save the tag. Personally, I would suggest keeping both "space" and "enter" as inputs to save the tags because I find pressing "space" counter-intuitive if you have only a single tag to save.

**Comment by guiweber** [comment]
p.s. It is the same in 1.4.3

**Comment by Rurik19** [comment]
Done with https://github.com/wallabag/wallabagger/commit/f32b00d12cb8a994e6f1384ca0d592c347baf25c
will be in the next version
